import { Artwork, Itinerary, TimelineEra } from "./types";

export const ARTWORKS: Artwork[] = [
  {
    id: "testa-michelangelo",
    title: "Testa rovesciata del David",
    title_it: "Testa rovesciata del David",
    artist: "Andrea Salvatori",
    description: "A contemporary reinterpretation of Michelangelo's David, hidden in the passage between Piazza San Carlo and Via Lagrange.",
    description_it: "Una reinterpretazione contemporanea del David di Michelangelo, nascosta nel passaggio tra Piazza San Carlo e Via Lagrange.",
    category: "contemporanea",
    type: "sculture",
    neighborhood: "centro",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    year: "2019",
    timeline_year: 2019,
    material_short: "Red earth",
    material_short_it: "Terra rossa",
    historical_context: "The Reversed Head of David is a contemporary work by Andrea Salvatori inspired by the famous head of Michelangelo's David. Located in the inner courtyard of Palazzo Villa, in the passage between Piazza San Carlo and Via Lagrange, it brings an absolute Renaissance reference into an everyday and almost hidden urban space. The work does not limit itself to quoting Michelangelo but reverses the image, transforming the classic model into a contemporary visual provocation.",
    historical_context_it: "La Testa rovesciata del David è un'opera contemporanea di Andrea Salvatori ispirata alla celebre testa del David di Michelangelo. Collocata nel cortile interno di Palazzo Villa, nel passaggio tra Piazza San Carlo e Via Lagrange, inserisce un riferimento assoluto del Rinascimento in uno spazio urbano quotidiano e quasi nascosto. L'opera non si limita a citare Michelangelo, ma ne ribalta l'immagine, trasformando il modello classico in una provocazione visiva contemporanea.",
    material_details: "The sculpture is made of red earth and is hollow inside. Those who approach can observe an internal surface painted blue and dotted with stars, an element that recalls the full title of the work and the reference to Kant's phrase about the starry sky and the moral law. The contrast between the earthy external matter and the celestial interior makes the sculpture simultaneously physical, fragile, and symbolic.",
    material_details_it: "La scultura è realizzata in terra rossa ed è cava all'interno. Chi si avvicina può osservare una superficie interna dipinta di blu e costellata di stelle, un elemento che richiama il titolo completo dell'opera e il riferimento alla frase di Kant sul cielo stellato e la legge morale. Il contrasto tra la materia terrosa esterna e l'interno celeste rende la scultura contemporaneamente fisica, fragile e simbolica.",
    reuse_context: "In the elegant context of Piazza San Carlo, the work introduces a poetic fracture: the classic is not exhibited as an untouchable model, but overturned, crossed, and transformed into an urban experience. The passerby thus discovers a Turin capable of hiding contemporary art inside historical and commercial places.",
    reuse_context_it: "Nell'elegante contesto di Piazza San Carlo, l'opera introduce una frattura poetica: il classico non viene esposto come un modello intoccabile, ma capovolto, attraversato e trasformato in un'esperienza urbana. Il passante scopre così una Torino capace di nascondere l'arte contemporanea all'interno di luoghi storici e commerciali.",
    image_url: "https://www.vivatorino.it/wp-content/uploads/2021/05/testa-capovolta-david-1.jpg",
    thumbnail_url: "https://www.vivatorino.it/wp-content/uploads/2021/05/testa-capovolta-david-1.jpg",
    image_alt: "La scultura Testa rovesciata del David di Andrea Salvatori",
    model_url: "/models/29_04_2026.glb",
    location: { address: "Piazza San Carlo, 161, Torino", lat: 45.0679, lng: 7.6836 }
  },
  {
    id: "toro-muro",
    title: "T'ORO - Il Toro che esce dal muro",
    title_it: "T'ORO - Il Toro che esce dal muro",
    artist: "Richi Ferrero",
    description: "A bull with golden horns seems to break through the wall of a historical building in the Quadrilatero Romano.",
    description_it: "Un toro con le corna d'oro sembra squarciare il muro di un edificio storico nel Quadrilatero Romano.",
    category: "contemporanea",
    type: "installazione-urbana",
    neighborhood: "quadrilatero",
    visibility: "iconico",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    timeline_year: 2018,
    material_short: "Mural installation",
    material_short_it: "Installazione murale",
    historical_context: "T'ORO is a contemporary work by Richi Ferrero located in via delle Orfane 20, in the Quadrilatero Romano. The work depicts a bull, symbol of the city of Turin, emerging from the wall of the Quadrato complex, an Urban Relais created in the context of the ancient convent of Sant'Agostino.",
    historical_context_it: "T'ORO è un'opera contemporanea di Richi Ferrero situata in via delle Orfane 20, nel Quadrilatero Romano. L'opera raffigura un toro, simbolo della città di Torino, che emerge dal muro del complesso Quadrato, un Urban Relais nato nel contesto dell'antico convento di Sant'Agostino.",
    material_details: "The work uses the wall as an active surface: the bull does not simply appear applied to the facade but seems to break the wall and come out into the urban space. The golden horns function as a central visual element, attracting the eye and transforming an architectural corner into a dynamic scene.",
    material_details_it: "L'opera utilizza la parete come superficie attiva: il toro non appare semplicemente applicato alla facciata, ma sembra rompere il muro e uscire nello spazio urbano. Le corna dorate fungono da elemento visivo centrale, attirando lo sguardo e trasformando un angolo architettonico in una scena dinamica.",
    reuse_context: "The bull breaking through the wall becomes a metaphor for the changing city. Inserted in an ancient and stratified neighborhood, the work creates a dialogue between the historical symbol of Turin and a contemporary language, suggesting that urban identity is not immobile but continues to re-emerge and transform.",
    reuse_context_it: "Il toro che squarcia la parete diventa una metafora della città che cambia. Inserita in un quartiere antico e stratificato, l'opera crea un dialogo tra il simbolo storico di Torino e un linguaggio contemporaneo, suggerendo che l'identità urbana non è immobile ma continua a riemergere e a trasformarsi.",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2019/09/toro-esce-muro-torino.jpg",
    thumbnail_url: "https://www.guidatorino.com/wp-content/uploads/2019/09/toro-esce-muro-torino.jpg",
    image_alt: "T'ORO, il toro che esce dal muro in via delle Orfane a Torino",
    location: { address: "Via delle Orfane, 20, Torino", lat: 45.0755, lng: 7.6793 }
  },
  {
    id: "l-eco",
    title: "Eco",
    title_it: "Eco",
    artist: "Marc Didou",
    description: "A sound sculpture composed of two mirror heads reflecting on the theme of urban communication.",
    description_it: "Uma scultura sonora composta da due teste speculari che riflettono sul tema della comunicazione urbana.",
    category: "contemporanea",
    type: "sculture",
    neighborhood: "centro",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    year: "2005",
    timeline_year: 2005,
    material_short: "Bronze, steel and concrete",
    material_short_it: "Bronzo, acciaio e cemento",
    historical_context: "Eco is a permanent urban art work created by Marc Didou and located in via Giuseppe Verdi, in the area of the Mole Antonelliana. It was conceived as part of the 'Cento Piazze per Torino' urban redevelopment competition, dedicated in this case to the theme of communication.",
    historical_context_it: "Eco è un'opera di arte urbana permanente realizzata da Marc Didou e situata in via Giuseppe Verdi, nella zona della Mole Antonelliana. È stata concepita nell'ambito del concorso di riqualificazione urbana 'Cento Piazze per Torino', dedicato in questo caso al tema della comunicazione.",
    material_details: "The sculpture represents two human heads superimposed in a mirror-like way, built through stratigraphic sections that recall medical imaging techniques such as MRI. It is made of bronze, stainless steel, and concrete. Inside there is a water system: approaching the sculpture you can perceive the sound of water, invisible but present.",
    material_details_it: "La scultura rappresenta due teste umane sovrapposte in modo speculare, costruite attraverso sezioni stratigrafiche che richiamano le tecniche di imaging medico come la risonanza magnetica. È realizzata in bronzo, acciaio inossidabile e cemento. All'interno è presente un sistema idrico: avvicinandosi alla scultura si può percepire il suono dell'acqua, invisibile ma presente.",
    reuse_context: "Eco transforms a university and city passage into a place of listening. Instead of communicating only through visual form, the work forces the visitor to slow down and use hearing as well. The theme of communication thus becomes a physical, urban, and sensory experience.",
    reuse_context_it: "Eco trasforma un passaggio universitario e cittadino in un luogo di ascolto. Invece di comunicare solo attraverso la forma visiva, l'opera costringe il visitatore a rallentare e ad usare anche l'udito. Il tema della comunicazione diventa così un'esperienza fisica, urbana e sensoriale.",
    thumbnail_url: "https://www.museotorino.it/images/74/0c/24/d4/740c24d4988c44edaeb8c41bda1b6282-3.jpg",
    image_alt: "La scultura Eco di Marc Didou in via Giuseppe Verdi a Torino",
    location: { address: "Via Giuseppe Verdi, 39, Torino", lat: 45.0679, lng: 7.6937 }
  },
  {
    id: "mole-antonelliana",
    title: "Mole Antonelliana",
    title_it: "Mole Antonelliana",
    artist: "Alessandro Antonelli",
    description: "The architectural symbol of Turin, born as a synagogue and today home to the National Museum of Cinema.",
    description_it: "Il simbolo architettonico di Torino, nato come sinagoga e oggi sede del Museo Nazionale del Cinema.",
    category: "monumento",
    type: "architettura",
    neighborhood: "vanchiglia",
    visibility: "iconico",
    period: "XIX Secolo",
    period_it: "XIX Secolo",
    year: "1863-1889",
    timeline_year: 1863,
    material_short: "Masonry, stone and metal structure",
    material_short_it: "Muratura, pietra e struttura metallica",
    historical_context: "The Mole Antonelliana was designed by Alessandro Antonelli and started in 1863 as a new synagogue for the Turin Jewish community. It was later purchased by the City of Turin and destined as a monument to national unity. Completed in 1889, it soon became the city's main architectural symbol.",
    historical_context_it: "La Mole Antonelliana fu progettata da Alessandro Antonelli e iniziata nel 1863 come nuova sinagoga per la comunità ebraica torinese. Fu successivamente acquistata dal Comune di Torino e destinata a monumento dell'unità nazionale. Completata nel 1889, divenne ben presto il principale simbolo architettonico della città.",
    material_details: "The Mole is famous for its exceptional vertical development and for its originally masonry structure. At approximately 167.5 meters high, it was one of the tallest masonry buildings in Europe at the time. The dome, the small temple, and the spire create an immediately recognizable urban profile.",
    material_details_it: "La Mole è celebre per il suo eccezionale sviluppo verticale e per la sua struttura originariamente in muratura. Con circa 167.5 metri d'altezza, all'epoca era uno degli edifici in muratura più alti d'Europa. La cupola, il tempietto e la guglia creano un profilo urbano immediatamente riconoscibile.",
    reuse_context: "The Mole is an emblematic case of functional and symbolic transformation: born as a religious building, it became a civic monument and is today the seat of the National Museum of Cinema. Its value lies not only in its form, but in its ability to change function while maintaining a strong centrality in the Turin imagination.",
    reuse_context_it: "La Mole è un caso emblematico di trasformazione funzionale e simbolica: nata come edificio religioso, è diventata monumento civico ed è oggi la sede del Museo Nazionale del Cinema. Il suo valore risiede non solo nella sua forma, ma nella sua capacità di cambiare funzione mantenendo una forte centralità nell'immaginario torinese.",
    image_url: "https://turinitalyguide.com/wp-content/uploads/2017/05/Mole-with-Turin-landscape-city-view.jpg",
    thumbnail_url: "https://turinitalyguide.com/wp-content/uploads/2014/01/Mole-768x1024.jpg",
    image_alt: "Mole antonelliana Simbolo di torino",
    before_image_url: "https://www.atlanteditorino.it/approfondimenti/img/MoleTifone.gif",
    after_image_url: "https://turinitalyguide.com/wp-content/uploads/2017/05/Mole-with-Turin-landscape-city-view.jpg",
    before_image_alt: "Immagine storica della Mole Antonelliana",
    after_image_alt: "Vista attuale della Mole Antonelliana",
    location: { address: "Via Montebello, 20, Torino", lat: 45.0689, lng: 7.6931 }
  },
  {
    id: "statua-emanuele-filiberto",
    title: "Monumento a Emanuele Filiberto (Caval ëd Bronz)",
    title_it: "Monumento a Emanuele Filiberto (Caval ëd Bronz)",
    artist: "Carlo Marochetti",
    description: "The famous equestrian statue in Piazza San Carlo, dedicated to the duke who moved the Savoy capital to Turin.",
    description_it: "La celebre statua equestre in Piazza San Carlo, dedicata al duca che trasferì la capitale sabauda a Torino.",
    category: "storica",
    type: "sculture",
    neighborhood: "centro",
    visibility: "iconico",
    period: "XIX Secolo",
    period_it: "XIX Secolo",
    year: "1838",
    timeline_year: 1838,
    material_short: "Bronze and marble",
    material_short_it: "Bronzo e marmo",
    historical_context: "The equestrian monument to Emanuele Filiberto of Savoy, known as Caval ëd Bronz, was created by Carlo Marochetti and inaugurated in 1838 in the center of Piazza San Carlo. It celebrates the duke who in 1563 moved the capital of the duchy from Chambéry to Turin, marking a fundamental turning point in the political history of the city.",
    historical_context_it: "Il monumento equestre a Emanuele Filiberto di Savoia, noto come Caval ëd Bronz, fu realizzato da Carlo Marochetti e inaugurato nel 1838 al centro di Piazza San Carlo. Celebra il duca che nel 1563 trasferì la capitale del ducato da Chambéry a Torino, segnando una svolta fondamentale nella storia politica della città.",
    material_details: "The bronze statue shows Emanuele Filiberto on horseback in a solemn and controlled pose. The base features reliefs related to the Battle of St. Quentin and the Treaty of Cateau-Cambrésis. The bronze gives the work a stable monumental presence, reinforced by its central position in the square.",
    material_details_it: "La statua di bronzo mostra Emanuele Filiberto su un cavallo in posa solenne e controllata. La base presenta rilievi legati alla Battaglia di San Quintino e al Trattato di Cateau-Cambrésis. Il bronzo conferisce all'opera una stabile presenza monumentale, rafforzata dalla posizione centrale nella piazza.",
    reuse_context: "The Caval ëd Bronz transforms Piazza San Carlo into a political and urban scene. Today it functions not only as a dynastic monument, but as a point of orientation, meeting, and collective recognition in the heart of historical Turin.",
    reuse_context_it: "Il Caval ëd Bronz trasforma Piazza San Carlo in una scena politica e urbana. Oggi funziona non solo come monumento dinastico, ma come punto di orientamento, incontro e riconoscimento collettivo nel cuore della Torino storica.",
    image_url: "https://c7.alamy.com/compit/3cf9wka/monumento-a-emanuele-filiberto-caval-d-brons-3cf9wka.jpg",
    thumbnail_url: "https://torinostoria.com/wp19/wp-content/uploads/2019/11/PIAZZA-SAN-CARLO_2019-2354.jpg",
    image_alt: "statua emanuele filiberto",
    location: { address: "Piazza San Carlo, Torino", lat: 45.0677, lng: 7.6827 }
  },
  {
    id: "porta-palatina",
    title: "Porta Palatina",
    title_it: "Porta Palatina",
    artist: "Epoca romana",
    description: "One of the best-preserved Roman city gates, material testimony of ancient Turin.",
    description_it: "Una delle porte romane meglio conservate al mondo, testimonianza materiale dell'antica Torino.",
    category: "monumento",
    type: "architettura",
    neighborhood: "centro",
    visibility: "iconico",
    period: "Epoca romana",
    period_it: "Epoca romana",
    year: "I Secolo",
    timeline_year: 1,
    material_short: "Brick and Roman masonry",
    material_short_it: "Mattoni e muratura romana",
    historical_context: "The Porta Palatina is one of the main remains of Roman Turin. It was a city gate of Augusta Taurinorum and represented a monumental access point to the city space. Over the centuries it lost its original function, was transformed and reused, until it was progressively isolated and restored as an archaeological monument.",
    historical_context_it: "La Porta Palatina è uno dei principali resti della Torino romana. Era una porta cittadina di Augusta Taurinorum e rappresentava un punto d'accesso monumentale allo spazio urbano. Nei secoli ha perso la sua funzione originaria, è stata trasformata e riutilizzata, fino a essere progressivamente isolata e restaurata come monumento archeologico.",
    material_details: "The structure preserves two tall side towers, a central body with carriage and pedestrian arches, and brick masonry with decorative architectural elements. The material of the gate still shows the defensive function and access control, but also the traces of subsequent transformations.",
    material_details_it: "La struttura conserva due alte torri laterali, un corpo centrale con archi carrai e pedonali, e una muratura in mattoni con elementi decorativi architettonici. Il materiale della porta mostra ancora la funzione difensiva e di controllo degli accessi, ma anche le tracce delle trasformazioni successive.",
    reuse_context: "Today the Porta Palatina no longer serves to defend or control the city, but to make its Roman origin legible. Inserted in the archaeological park, it becomes a narrative threshold: the visitor ideally crosses the passage between contemporary Turin and Augusta Taurinorum.",
    reuse_context_it: "Oggi la Porta Palatina non serve più a difendere o controllare la città, ma a renderne leggibile l'origine romana. Inserita nel parco archeologico, diventa una soglia narrativa: il visitatore attraversa idealmente il confine tra la Torino contemporanea e Augusta Taurinorum.",
    image_url: "https://www.tedxtorino.com/2017/wp-content/uploads/2017/09/Porta_Palatina_-_panoramio.jpg",
    thumbnail_url: "https://www.tedxtorino.com/2017/wp-content/uploads/2017/09/Porta_Palatina_-_panoramio.jpg",
    image_alt: "Porta palatina",
    before_image_url: "https://mole24.it/wp-content/uploads/2020/11/1000_Ricostruzione-1-1024x1016.jpg",
    after_image_url: "https://www.tedxtorino.com/2017/wp-content/uploads/2017/09/Porta_Palatina_-_panoramio.jpg",
    before_image_alt: "Immagine storica della Mole Antonelliana",
    after_image_alt: "Vista attuale della Mole Antonelliana",
    location: { address: "Piazza Cesare Augusto, Torino", lat: 45.0750, lng: 7.6847 }
  },
  {
    id: "palazzo-piercing",
    title: "Baci Urbani (Palazzo con il Piercing)",
    title_it: "Baci Urbani (Palazzo con il Piercing)",
    artist: "Corrado Levi e Cliostraat",
    description: "A large metal piercing pierces the corner of an eighteenth-century palace in the center of Turin.",
    description_it: "Un grande piercing metallico trafigge l'angolo di un palazzo settecentesco nel centro di Torino.",
    category: "hidden-art",
    type: "installazione-urbana",
    neighborhood: "centro",
    visibility: "poco-conosciuto",
    period: "Postmoderno",
    period_it: "Postmoderno",
    year: "1996",
    timeline_year: 1996,
    material_short: "Steel and paint",
    material_short_it: "Acciaio e vernice",
    historical_context: "Urban Kisses, known as the Palace with the Piercing, is a contemporary installation created by Corrado Levi in collaboration with the group Cliostraat. Born as a temporary intervention, it remained on the corner of the building in via Palazzo di Città 19, near Piazza Castello, becoming one of the most recognizable urban curiosities in the center.",
    historical_context_it: "Baci Urbani, noto come il Palazzo con il Piercing, è un'installazione contemporanea creata da Corrado Levi in collaborazione con il gruppo Cliostraat. Nata come intervento temporaneo, è rimasta sull'angolo dell'edificio in via Palazzo di Città 19, vicino a Piazza Castello, diventando una delle curiosità urbane più riconoscibili del centro.",
    material_details: "The work consists of a large metal ring applied to the corner of the fourth floor of the building. On the sides appear two droplets of red and blue color, interpreted as a reference to the double soul of the city: the popular one and the noble one. The historical facade is treated as an urban skin crossed by a contemporary sign.",
    material_details_it: "L'opera consiste in un grande anello di metallo applicato all'angolo del quarto piano dell'edificio. Ai lati compaiono due gocce di colore rosso e blu, interpretate come riferimento alla doppia anima della città: quella popolare e quella nobile. La facciata storica è trattata come una pelle urbana attraversata da un segno contemporaneo.",
    reuse_context: "The piercing does not erase the architectural tradition but inserts itself in a provocative way. The work makes visible the dialogue between Savoy Turin and contemporary urban languages, transforming a facade detail into a small social narrative.",
    reuse_context_it: "Il piercing non cancella la tradizione architettonica, ma vi si inserisce in modo provocatorio. L'opera rende visibile il dialogo tra la Torino sabauda e i linguaggi urbani contemporanei, trasformando un dettaglio di facciata in una prima narrazione sociale.",
    image_url: "https://www.tastingtheworld.it/wp-content/uploads/2013/01/piercing-urbano-torino-baci-urbani.jpg",
    thumbnail_url: "https://www.tastingtheworld.it/wp-content/uploads/2013/01/piercing-urbano-torino-baci-urbani.jpg",
    image_alt: "Palazzo piercing",
    location: { address: "Via Palazzo di Città, 19, Torino", lat: 45.0725, lng: 7.6824 }
  },
  {
    id: "palle-cannone",
    title: "Le Palle di Cannone dell'Assedio",
    title_it: "Le Palle di Cannone dell'Assedio",
    artist: "Memoria degli assedi di Torino",
    description: "Bullets embedded in the facades of the historic center recall the sieges and bombings suffered by the city.",
    description_it: "I proiettili incastonati nelle facciate del centro storico ricordano gli assedi e i bombardamenti subiti dalla città.",
    category: "hidden-art",
    type: "sculture",
    neighborhood: "quadrilatero",
    visibility: "molto-nascosto",
    period: "XVIII Secolo",
    period_it: "XVIII Secolo",
    year: "1706 / 1799",
    timeline_year: 1706,
    material_short: "Iron and masonry",
    material_short_it: "Ferro e muratura",
    historical_context: "The cannonballs visible on some Turin facades are testimonies of the sieges and bombings suffered by the city, particularly in 1706 and 1799. Some projectiles were intentionally walled into the buildings to preserve the memory of those critical moments and the resistance of the city.",
    historical_context_it: "Le palle di cannone visibili su alcune facciate di Torino sono testimonianze degli assedi e dei bombardamenti subiti dalla città, in particolare nel 1706 e nel 1799. Alcuni proiettili sono stati murati intenzionalmente negli edifici per conservare la memoria di quei momenti critici e della resistenza della città.",
    material_details: "The material value of the work lies in the contrast between the iron of the projectiles and the stone or plaster of the facades. These are not decorations, but war fragments transformed into traces permanent. The material preserves the trauma instead of erasing it.",
    material_details_it: "Il valore materiale risiede nel contrasto tra il ferro dei proiettili e la pietra o l'intonaco delle facciate. Non si tratta di decorazioni, ma di frammenti di guerra trasformati in tracce permanenti. Il materiale conserva il trauma invece di cancellarlo.",
    reuse_context: "These cannonballs transform the city walls into a widespread archive. The visitor encounters the memory of war not inside a museum, but in the daily surfaces of buildings, where history remains embedded in the urban fabric.",
    reuse_context_it: "Queste palle di cannone trasformano le pareti cittadine in un archivio diffuso. Il visitatore incontra la memoria della guerra non dentro un museo, ma nelle superfici quotidiane dei palazzi, dove la storia rimane incastonata nel tessuto urbano.",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2025/02/palle-cannone-palazzi-torino-633x400.jpg",
    thumbnail_url: "https://www.guidatorino.com/wp-content/uploads/2025/02/palle-cannone-palazzi-torino-633x400.jpg",
    image_alt: "Palla di cannone incastonata in una facciata storica di Torino",
    location: { address: "Via delle Orfane, 20, Torino", lat: 45.0676, lng: 7.6830 }
  },
  {
    id: "orso-bordalo",
    title: "The Big Bear",
    title_it: "The Big Bear",
    artist: "Bordalo II",
    description: "A huge bear built with waste materials observes passers-by from the side wall of the Colosseo Theater.",
    description_it: "Un enorme orso costruito con materiali di scarto osserva i passanti dalla parete laterale del Teatro Colosseo.",
    category: "hidden-art",
    type: "murale",
    neighborhood: "san-salvario",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    year: "2016",
    timeline_year: 2016,
    material_short: "Trash and recycled materials",
    material_short_it: "Rifiuti e materiali riciclati",
    historical_context: "The Big Bear is a work by the Portuguese artist Bordalo II, created in 2016 on the side wall of the Teatro Colosseo, in via Giorgio Bidone, in the San Salvario district. It is part of the Big Trash Animals series, with which the artist represents monumental animals using waste and scrap materials.",
    historical_context_it: "The Big Bear è un'opera dell'artista portoghese Bordalo II, realizzata nel 2016 sulla parete laterale del Teatro Colosseo, in via Giorgio Bidone, nel quartiere San Salvario. Fa parte della serie 'Big Trash Animals', con cui l'artista rappresenta animali monumentali utilizzando rifiuti e materiali di recupero industriali e urbani.",
    material_details: "The bear is composed of recovered objects such as bicycle frames, sheets, bins, and other discarded urban materials. The three-dimensional assembly technique makes the work a cross between a sculpture, a mural, and an environmental installation. The material is not neutral: waste is an essential part of the message.",
    material_details_it: "L'orso è composto da oggetti recuperati come telai di biciclette, lamiere, cassonetti e altri materiali urbani dismessi. La tecnica di assemblaggio tridimensionale rende l'opera una via di mezzo tra una scultura, un murale e un'installazione ambientale. Il materiale non è neutro: lo scarto è parte integrante del messaggio.",
    reuse_context: "The work transforms the theater facade into an ecological manifesto. Representing an animal with the waste produced by urban society creates a short circuit between nature and consumption, making the wall a place of environmental denunciation and visual regeneration.",
    reuse_context_it: "L'opera trasforma la facciata del teatro in un manifesto ecologico. Rappresentare un animal con i rifiuti prodotti dalla società urbana crea un cortocircuito tra natura e consumo, rendendo la parete un luogo di denuncia ambientale e rigenerazione visiva.",
    image_url: "https://c7.alamy.com/compit/2ap2d9p/l-orso-opera-dell-artista-di-strada-portoghese-bordalo-ii-sulla-parete-laterale-del-teatro-colosseo-nel-quartiere-di-san-salvario-torino-piemonte-italia-2ap2d9p.jpg",
    thumbnail_url: "https://streetartutopia.com/wp-content/uploads/2016/12/Street-Art-by-Bordalo-II-in-Turin-Italy-at-teartrocolosseo-Bear.jpg",
    image_alt: "The Big Bear",
    location: { address: "Via Giorgio Bidone, 30, Torino", lat: 45.0522, lng: 7.6793 }
  },
  {
    id: "dito-colombo",
    title: "Il Dito di Colombo",
    title_it: "Il Dito di Colombo",
    artist: "Dino Somà",
    description: "Columbus's bronze pinky finger, worn down by passers-by, has become a Turin good luck ritual.",
    description_it: "Il mignolo di bronzo di Colombo, logorato dal tocco dei passanti, è diventato un rito scaramantico torinese.",
    category: "hidden-art",
    type: "sculture",
    neighborhood: "centro",
    visibility: "iconico",
    period: "XX Secolo",
    period_it: "XX Secolo",
    year: "1923",
    timeline_year: 1923,
    material_short: "Bronze",
    material_short_it: "Bronzo",
    historical_context: "Columbus's Finger is part of a bronze bas-relief medallion dedicated to Christopher Columbus, located under the porticoes of the Prefecture in Piazza Castello, near the Royal Library. It was created by Dino Somà and inaugurated in 1923 to commemorate the participation of Italian emigrants in Latin America in the First World War.",
    historical_context_it: "Il Dito di Colombo fa parte di un medaglione bronzeo ad altorilievo dedicato a Cristoforo Colombo, situato sotto i portici della Prefettura in Piazza Castello, nei pressi della Biblioteca Reale. Fu realizzato da Dino Somà e inaugurato nel 1923 per commemorare la partecipazione degli emigrati italiani in America Latina alla prima guerra mondiale.",
    material_details: "The most evident detail is the pinky finger of Columbus's hand, much shinier than the rest of the bronze due to constant rubbing by passers-by. The consumption of the surface has become an integral part of the work, making visible the physical relationship between monument and public.",
    material_details_it: "Il dettaglio più evidente è il dito mignolo della mano di Colombo, molto più lucido rispetto al resto del bronzo a causa del costante sfregamento da parte dei passanti. L'usura della superficie è diventata parte integrante dell'opera, rendendo visibile il rapporto fisico tra monumento e pubblico.",
    reuse_context: "Popular tradition has it that touching the finger brings good luck, especially to students before exams. The monument has thus taken on a second life: from historical memory it has become a daily gesture, urban superstition, and collective ritual.",
    reuse_context_it: "La tradizione popolare vuole che sfiorare il dito porti fortuna, in particolare agli studenti prima degli esami. Il monumento ha così assunto una seconda vita: da memoria storica è diventato gesto quotidiano, superstizione urbana e rituale collettivo.",
    image_url: "https://offloadmedia.feverup.com/torinosegreta.com/wp-content/uploads/2022/03/24034239/dito-colombo-torino-1024x683.png",
    thumbnail_url: "https://www.cristoforocolombo.com/wp-content/uploads/2016/12/COLOMBO-ARTE-mignolo-Cristoforo-e-compasso-DOC-DOC-DOC.jpg",
    image_alt: "Dito di colombo",
    location: { address: "Piazza Castello, Torino", lat: 45.0712, lng: 7.6868 }
  },
  {
    id: "panchina-innamorati",
    title: "La Panchina degli Innamorati",
    title_it: "La Panchina degli Innamorati",
    artist: "Rodolfo Marasciuolo",
    description: "Two anthropomorphic street lamps embrace on a bench in the Rocky Garden of the Valentino.",
    description_it: "Due lampioni antropomorfi si abbracciano su una panchina nel Giardino Roccioso del Valentino.",
    category: "hidden-art",
    type: "installazione-urbana",
    neighborhood: "borgo-po",
    visibility: "iconico",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    timeline_year: 2010,
    material_short: "Iron and street furniture",
    material_short_it: "Ferro e arredo urbano",
    historical_context: "The Lovers' Bench, also called Innamorati Lamps, is located in the Garden Rocky area of the Parco del Valentino, near the Medieval Village. The work was created by Rodolfo Marasciuolo, a gardener-artist known for enriching Turin's green spaces with poetic installations.",
    historical_context_it: "La Panchina degli Innamorati, detta anche i Lampioni Innamorati, si trova nella zona del Giardino Roccioso all'interno del Parco del Valentino, vicino al Borgo Medievale. L'opera è stata realizzata da Rodolfo Marasciuolo, un giardiniere-artista noto per arricchire le aree verdi torinesi con installazioni poetiche.",
    material_details: "The work transforms ordinary street furniture elements into affective figures. Two street lamps are represented as characters sitting on a bench, one of which seems to rest its head on the other's shoulder. Iron, a normally cold and functional material, becomes a vehicle for tenderness and complicity.",
    material_details_it: "L'opera trasforma i comuni elementi dell'arredo urbano in figure affettive. Due lampioni sono rappresentati come figure sedute su una panchina, una delle quali sembra appoggiare la testa sulla spalla dell'altra. Il ferro, materiale freddo e funzionale, diventa un veicolo di tenerezza e complicità.",
    reuse_context: "In the quiet landscape of the Valentino, the bench becomes a place of pause and interpretation. It does not tell a great historical event, but enhances an everyday and relational dimension of the city: love, the pause, the simple shared gesture in public space.",
    reuse_context_it: "Nel tranquillo paesaggio del Valentino, la panchina diventa un luogo di sosta e interpretazione. Non racconta un grande evento storico, ma valorizza una dimensione quotidiana e relazionale della città: l'amore, la pausa, il semplice gesto condiviso nello spazio pubblico.",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2022/01/panchina-innamorati-torino-633x400.jpg",
    thumbnail_url: "https://i.pinimg.com/736x/ef/4c/c5/ef4cc527c80d1bdda5509bfbbf6b19bf.jpg",
    image_alt: "La Panchina degli Innamorati nel Giardino Roccioso del Valentino",
    location: { address: "Giardino Roccioso, Parco del Valentino, Torino", lat: 45.0497, lng: 7.6842 }
  },
  {
    id: "condominio-25-verde",
    title: "Condominio 25 Verde",
    title_it: "Condominio 25 Verde",
    artist: "Luciano Pia",
    description: "An eco-sustainable residential building that integrates architecture, vegetation and urban life.",
    description_it: "Un edificio residenziale eco-sostenibile che integra architettura, vegetazione e vita urbana.",
    category: "contemporanea",
    type: "architettura",
    neighborhood: "san-salvario",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    year: "2010-2013",
    timeline_year: 2010,
    material_short: "Steel, wood and vegetation",
    material_short_it: "Acciaio, legno e vegetazione",
    historical_context: "The 25 Verde Condominium is a residential building designed by Luciano Pia in via Gabriele Chiabrera 25, in the San Salvario district. Built between 2010 and 2013 and inaugurated in 2014, it represents one of the most well-known Turin cases of eco-sustainable bioarchitecture.",
    historical_context_it: "Il Condominio 25 Verde è un edificio residenziale progettato da Luciano Pia in via Gabriele Chiabrera 25, nel quartiere San Salvario. Costruito tra il 2010 e il 2013 e inaugurato nel 2014, rappresenta uno dei più famosi casi torinesi di bioarchitettura eco-sostenibile.",
    material_details: "The building combines steel, wood, and vegetation. The metallic structures recall trunks and branches, the wooden cladding evokes bark, and the presence of trees, green terraces, and roof gardens changes the appearance of the building over time. Vegetation is not simple decoration, but part of the environmental behavior of the architecture.",
    material_details_it: "L'edificio combina acciaio, legno e vegetazione. Le strutture metalliche ricordano tronchi e rami, il rivestimento in legno evoca la corteccia, e la presenza di alberi, terrazzi verdi e tetti fioriti cambia l'aspetto del condominio col mutare delle stagioni. La vegetazione non è semplice decoro, ma parte attiva del comportamento ambientale dell'architettura.",
    reuse_context: "25 Verde proposes a different idea of urban living: it does not separate home and nature but overlaps them. In the dense fabric of San Salvario, the building becomes an experiment in coexistence between residence, microclimate, vegetation, and city landscape.",
    reuse_context_it: "25 Verde propone un'idea diversa di abitare urbano: non separa casa e natura, ma le sovrappone. Nel fitto tessuto di San Salvario, l'edificio diventa un esperimento di coesistenza tra residenza, microclima, vegetazione e paesaggio cittadino.",
    image_url: "https://www.secondamanoitalia.it/wp-content/uploads/2021/12/condominio-25-verde-1024x683.jpg",
    thumbnail_url: "https://www.openhousetorino.it/wp-content/gallery/25-verde/thumbs/thumbs_25-verde%40Fabrizio-Mauro_1.jpg",
    image_alt: "Condominio 25 Verde a Torino",
    before_image_alt: "Immagine storica della Mole Antonelliana",
    after_image_alt: "Vista attuale della Mole Antonelliana",
    location: { address: "Via Gabriele Chiabrera, 25, Torino", lat: 45.0454, lng: 7.6800 }
  },
  {
    id: "sommergibile-provana",
    title: "Sommergibile Andrea Provana",
    title_it: "Sommergibile Andrea Provana",
    artist: "Cantieri Fiat San Giorgio",
    description: "A section of a World War I submarine preserved in the Valentino Park.",
    description_it: "Una sezione di un sommergibile della prima guerra mondiale custodita nel Parco del Valentino.",
    category: "monumento",
    type: "installazione-urbana",
    neighborhood: "borgo-po",
    visibility: "poco-conosciuto",
    period: "Prima Guerra Mondiale",
    period_it: "Prima Guerra Mondiale",
    year: "1915-1928",
    timeline_year: 1915,
    material_short: "Naval steel",
    material_short_it: "Acciaio navale",
    historical_context: "The Andrea Provana submarine was built in 1915 in the Fiat San Giorgio shipyards of La Spezia and launched in 1918 by the Royal Navy. It did not participate in war actions during the First World War but was used for training activities. Its central section was brought to Turin for the 1928 Exhibition and subsequently placed in the Valentino Park.",
    historical_context_it: "Il sommergibile Andrea Provana fu costruito nel 1915 nei cantieri Fiat San Giorgio di La Spezia e varato nel 1918 dalla Regia Marina. Non partecipò ad azioni belliche durante la prima guerra mondiale, ma fu impiegato per attività di addestramento. La sua sezione centrale fu portata a Torino per l'Esposizione del 1928 e successivamente collocata nel Parco del Valentino.",
    material_details: "Not the entire submarine is preserved in Turin, but the central section with conning tower and cannons. The metallic material, thought for the marine and military environment, appears strongly clinical in the green of the park and along the banks of the Po. Precisely this contrast makes the find particularly recognizable.",
    material_details_it: "A Torino non è conservato l'intero sommergibile, ma la sezione centrale con la torretta di comando e i cannoni. Il materiale metallico, pensato per l'ambiente marino e militare, appare fortemente insolito nel verde del parco e lungo le sponde del Po. Proprio questo contrasto rende il reperto particolarmente riconoscibile.",
    reuse_context: "The Provana is interesting because it completely changes context: from a naval and military machine it becomes an urban find and visitable memory. In the Valentino, war technology loses its original function and is transformed into a historical document accessible to the public.",
    reuse_context_it: "Il Provana è interessante perché cambia completamente contesto: da macchina bellica e navale diventa reperto urbano e memoria visitabile. Al Valentino, la tecnologia bellica perde la sua funzione originaria e si trasforma in un documento storico accessibile al pubblico.",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2019/08/sommergibile-torino-provana-633x400.jpg",
    thumbnail_url: "https://www.guidatorino.com/wp-content/uploads/2019/08/sommergibile-torino-provana-633x400.jpg",
    image_alt: "Il sommergibile Andrea Provana nel Parco del Valentino",
    location: { address: "Viale Marinai d'Italia, 1, Torino", lat: 45.0449, lng: 7.6838 }
  },
  {
    id: "palazzo-madama",
    title: "Palazzo Madama",
    title_it: "Palazzo Madama",
    artist: "Filippo Juvarra e trasformazioni precedenti",
    description: "A stratified building that summarizes two thousand years of Turin history, from the Roman gate to the city museum.",
    description_it: "Un edificio stratificato che riassume duemila anni di storia torinese, dalla porta romana al museo civico.",
    category: "monumento",
    type: "architettura",
    neighborhood: "centro",
    visibility: "iconico",
    period: "Romano / Medievale / Barocco",
    period_it: "Romano / Medievale / Barocco",
    year: "I Secolo - XVIII Secolo",
    timeline_year: 1718,
    material_short: "Brick, stone and historical masonry",
    material_short_it: "Mattoni, pietra e muratura storica",
    historical_context: "Palazzo Madama is one of the most stratified buildings in Turin. Its history starts from the Roman gate incorporated into the structure, goes through the medieval phase of the castle and arrives at the Baroque and court transformation, with the large facade designed by Filippo Juvarra. Today it houses the Civic Museum of Ancient Art.",
    historical_context_it: "Palazzo Madama è uno dei palazzi più stratificati di Torino. La sua storia inizia dalla porta romana incorporata nella struttura, passa attraverso la fase medievale del castello e giunge alla trasformazione barocca e di corte, con la grande facciata progettata da Filippo Juvarra. Oggi ospita il Museo Civico d'Arte Antica.",
    material_details: "The palace shows materials, forms, and languages belonging to different eras: Roman remains, medieval structures, towers, representation rooms, and Baroque facade. Its architectural material is a palimpsest: it does not erase previous phases, but makes them legible in the same building body.",
    material_details_it: "Il palazzo mostra materiali, forme e linguaggi appartenenti a epoche diverse: resti romani, strutture medievali, torri, saloni di rappresentanza e facciata barocca. La sua materia architettonica è un palinsesto: non cancella le fasi precedenti, ma le rende leggibili nello stesso corpo di fabbrica.",
    reuse_context: "Palazzo Madama is a synthesis of the city itself. From defensive structure to residence, from place of power to museum, it demonstrates how urban heritage can change function without losing historical depth. Its current identity arises precisely from the overlap of uses and meanings.",
    reuse_context_it: "Palazzo Madama è una sintesi della città stessa. Da struttura difensiva a residenza, da luogo di potere a museo, dimostra come il patrimonio urbano possa cambiare funzione senza perdere spessore storico. La sua identità attuale nasce proprio dalla sovrapposizione di usi e significati.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Palazzo_Madama%2C_Torino_crop.jpg/960px-Palazzo_Madama%2C_Torino_crop.jpg",
    thumbnail_url: "https://traveldigg.com/wp-content/uploads/2016/09/Palazzo-Madama-Front-Photo.jpg",
    image_alt: "Palazzo Madama in Piazza Castello a Torino",
    before_image_url: "https://www.museotorino.it/images/71/2a/a0/cd/712aa0cd3d594827b27191b6151e48f4-1.jpg",
    after_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Palazzo_Madama%2C_Torino_crop.jpg/960px-Palazzo_Madama%2C_Torino_crop.jpg",
    before_image_alt: "Immagine storica della Mole Antonelliana",
    after_image_alt: "Vista attuale della Mole Antonelliana",
    location: { address: "Piazza Castello, Torino", lat: 45.0708, lng: 7.6855 }
  },
  {
    id: "cappella-sindone",
    title: "Cappella della Sacra Sindone",
    title_it: "Cappella della Sacra Sindone",
    artist: "Guarino Guarini",
    description: "A Baroque masterpiece designed to house the Shroud, marked by the 1997 fire and the long restoration.",
    description_it: "Un capolavoro del barocco progettato per custodire la Sindone, segnato dall'incendio del 1997 e dal lungo restauro.",
    category: "monumento",
    type: "architettura",
    neighborhood: "centro",
    visibility: "iconico",
    period: "Barocco",
    period_it: "Barocco",
    year: "1668-1694",
    timeline_year: 1668,
    material_short: "Black Frabosa marble",
    material_short_it: "Marmo nero di Frabosa",
    historical_context: "The Chapel of the Holy Shroud was designed by Guarino Guarini between the Cathedral and the Royal Palace to house the Shroud. It is one of the masterpieces of European Baroque and one of the most significant places in Savoy Turin. After the serious fire of 1997, it underwent a long restoration and reopened to the public in 2018.",
    historical_context_it: "La Cappella della Sacra Sindone fu progettata da Guarino Guarini tra il Duomo e il Palazzo Reale per custodire la Sindone. È uno dei capolavori del barocco europeo e uno dei luoghi più significativi della Torino sabauda. Dopo il grave incendio del 1997, ha subito un lungo restauro ed è stata riaperta al pubblico nel 2018.",
    material_details: "The chapel is characterized by the use of black marble, a complex geometric structure, and a dome built as an optical and symbolic machine. The material also preserves the memory of the damage: the restoration had to deal with fractures, high temperatures, replacements, and recoveries of stone elements.",
    material_details_it: "La cappella si caratterizza per l'uso del marmo nero, una complessa struttura geometrica e una cupola costruita come macchina ottica e simbolica. Il materiale conserva anche la memoria del danno: il restauro ha dovuto confrontarsi con le fessurazioni, le alte temperature, le sostituzioni e i recuperi degli elementi lapidei.",
    reuse_context: "Today the Shroud Chapel tells not only of religious devotion and Savoy power, but also of the fragility of heritage. Its contemporary value lies in the relationship between ruin, restoration, and public restitution: the monument survived thanks to new material care and interpretation.",
    reuse_context_it: "Oggi la Cappella della Sindone racconta non solo la devozione religiosa e il potere sabaudo, ma anche la fragilità del patrimonio. Il suo valore contemporaneo risiede nel rapporto tra rovina, restauro e restituzione pubblica: il monumento è sopravvissuto grazie a nuove cure materiali e interpretative.",
    image_url: "https://cosediviaggio.it/wp-content/uploads/2020/11/duomo-di-torino.jpg",
    thumbnail_url: "https://www.guidatorino.com/wp-content/uploads/2018/09/cappella-sindone-torino-7-633x400.jpg",
    image_alt: "La Cappella della Sacra Sindone a Torino",
    before_image_url: "https://upload.wikimedia.org/wikipedia/it/8/89/Incendio_Sindone_1.jpg",
    after_image_url: "https://cosediviaggio.it/wp-content/uploads/2020/11/duomo-di-torino.jpg",
    before_image_alt: "Immagine storica della cappella-sindone",
    after_image_alt: "Vista attuale del duomo",
    location: { address: "Piazza Duomo, Torino", lat: 45.0732, lng: 7.6859 }
  },
  {
    id: "musei-reali",
    title: "Musei Reali",
    title_it: "Musei Reali",
    artist: "Vari",
    description: "A large museum complex that collects the political, artistic and dynastic memory of Savoy Turin.",
    description_it: "Un grande complesso museale che unisce la memoria politica, artistica e dinastica della Torino sabauda.",
    category: "monumento",
    type: "architettura",
    neighborhood: "centro",
    visibility: "iconico",
    period: "XVI-XIX Secolo",
    period_it: "XVI-XIX Secolo",
    year: "1563",
    timeline_year: 1563,
    material_short: "Stone, marble, historical collections",
    material_short_it: "Pietra, marmo e collezioni storiche",
    historical_context: "The Royal Museums bring together some of the fundamental places of Savoy and city history, including the Royal Palace, Royal Armory, Shroud Chapel, Sabauda Gallery, Museum of Antiquity, Royal Library, and Royal Gardens. The complex is located in the heart of the ancient center and represents the transformation of the seat of power into public heritage.",
    historical_context_it: "I Musei Reali riuniscono alcuni dei luoghi fondamentali della storia sabauda e cittadina, tra cui il Palazzo Reale, l'Armeria Reale, la Cappella della Sindone, la Galleria Sabauda, il Museo di Antichità, la Biblioteca Reale e i Giardini Reali. Il complesso si trova nel cuore del centro antico e rappresenta la trasformazione della sede del potere in patrimonio pubblico.",
    material_details: "The material value of the complex lies in the variety of its environments and collections: representation rooms, weapons, works of art, archaeological finds, books, gardens, and monumental architecture. Each section preserves different materials, but all contribute to the construction of the historical image of the Savoy dynasty.",
    material_details_it: "Il valore materiale del complesso risiede nella varietà dei suoi ambienti e delle sue collezioni: sale di rappresentanza, armi, opere d'arte, reperti archeologici, volumi, giardini e architetture monumentali. Ogni sezione conserva materiali differenti, ma tutti concorrono alla costruzione dell'immagine storica della dinastia sabauda.",
    reuse_context: "The ancient seat of monarchic power is today a museum hub open to citizens and visitors. What once represented authority and selective access is reinterpreted as a space for knowledge, visiting, and cultural sharing.",
    reuse_context_it: "L'antica sede del potere monarchico è oggi un polo museale aperto a cittadini e visitatori. Quello che un tempo era rappresentanza dell'autorità e dell'accesso selettivo viene reinterpretato come spazio di conoscenza, visita e condivisione culturale.",
    image_url: "https://museireali.beniculturali.it/wp-content/uploads/2023/06/banner-organizza-la-tua-visita-1-1280x663.jpg",
    thumbnail_url: "https://scorcidimondo.it/wp-content/uploads/2022/02/PSX_20220209_103924-scaled.jpg",
    image_alt: "palazzo reale di Torino",
    location: { address: "Piazzetta Reale, 1, Torino", lat: 45.0725, lng: 7.6860 }
  },
  {
    id: "mau-assenza",
    title: "L'assenza",
    title_it: "L'assenza",
    artist: "Nice & the fox + Vito Navolio",
    description: "A mural that addresses the theme of memory and loss through an intense portrait and vital colors.",
    description_it: "Un murale che affronta il tema della memoria e della perdita attraverso un intenso ritratto e colori vitali.",
    category: "hidden-art",
    type: "murale",
    neighborhood: "campidoglio",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    year: "2023",
    timeline_year: 2023,
    material_short: "Mural painting",
    material_short_it: "Pittura murale",
    historical_context: "L'assenza is a work by MAU created by Nice & the fox along with Vito Navolio in via Nicola Fabrizi 21. The work belongs to the recent phase of the Museum of Urban Art, confirming the vitality of the Borgo Campidoglio project as a widespread and updatable museum over time.",
    historical_context_it: "L'assenza è un'opera del MAU realizzata da Nice & the fox insieme a Vito Navolio in via Nicola Fabrizi 21. L'opera appartiene alla fase recente del Museo d'Arte Urbana, confermando la vitalità del progetto di Borgo Campidoglio come museo diffuso e aggiornabile nel tempo.",
    material_details: "The mural occupies the wall of a corner building and depicts a male portrait framed by brilliant chromatic fields and stylized vegetable motifs. The contrast between realistic face and abstract background produces a strong visual impact.",
    material_details_it: "Il murale occupa la parete di un edificio d'angolo e raffigura un ritratto maschile incorniciato da brillanti campi cromatici e motivi vegetali stilizzati. Il contrasto tra ritratto realistico e sfondo astratto produce un forte impatto visivo.",
    reuse_context: "The work transforms an urban facade into a space of emotional memory. The theme of absence is made public and shared, while the colors and natural elements suggest a tension towards vitality and hope.",
    reuse_context_it: "L'opera trasforma una facciata urbana in uno spazio di memoria emotiva. Il tema dell'assenza viene reso pubblico e condiviso, mentre i colori e gli elementi naturali suggeriscono una tensione verso la vitalità e la speranza.",
    image_url: "https://civico20-news.it/wp-content/uploads/2024/06/Diapositiva3-17.jpeg",
    thumbnail_url: "https://civico20-news.it/wp-content/uploads/2024/06/Diapositiva3-17.jpeg",
    image_alt: "Murale L'assenza di Nice & the fox e Vito Navolio",
    location: { address: "Via Nicola Fabrizi 21, Torino", lat: 45.0839, lng: 7.6568 }
  },
  {
    id: "mau-campidoglius",
    title: "Campidoglius",
    title_it: "Campidoglius",
    artist: "Antonio Mascia",
    description: "A large red sea creature animates a wall in Piazza Moncenisio, transforming the neighborhood into a fanstastic tale.",
    description_it: "Una grande creatura marina rossa anima un muro in Piazza Moncenisio, trasformando il quartiere in un racconto fantastico.",
    category: "hidden-art",
    type: "murale",
    neighborhood: "campidoglio",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    year: "2001 / remake 2024",
    timeline_year: 2001,
    material_short: "Mural painting",
    material_short_it: "Pittura murale",
    historical_context: "Campidoglius is a work by Antonio Mascia created in the context of the MAU in Piazza Moncenisio 15. The original work dates back to 2001 and was reinterpreted in 2024, as part of the maintenance and renewal process of the urban museum's works.",
    historical_context_it: "Campidoglius è un'opera di Antonio Mascia realizzata nell'ambito del MAU in Piazza Moncenisio 15. L'opera originale risale al 2001 ed è stata reinterpretata nel 2024, nel quadro delle attività di manutenzione e rinnovo delle opere del museo urbano.",
    material_details: "The mural depicts a large red sea creature, a female figure with a diving mask, fish, and aquatic animals. The 2024 version also introduces an elderly reader sitting, observing and taking notes. The Campidoglio lettering explicitly links the work to the neighborhood.",
    material_details_it: "Il murale raffigura una grande creatura marina rossa, una figura femminile con maschera da sub, pesci e animali acquatici. La versione del 2024 introduce anche un anziano lettore seduto, intento ad osservare e prendere appunti. La scritta 'Campidoglio' lega esplicitamente l'opera al quartiere.",
    reuse_context: "Campidoglius transforms the wall into a narrative and fantastic device. The 2024 remake shows well how the MAU is not a stationary archive, but a living urban heritage, subject to care, updating, and reinterpretation.",
    reuse_context_it: "Campidoglius trasforma la parete in un dispositivo narrativo e fantastico. Il remake del 2024 mostra bene come il MAU non sia un archivio immobile, ma un patrimonio urbano vivo, oggetto di cura, ripresa e aggiornamento.",
    image_url: "https://www.museoarteurbana.it/wp-content/uploads/2025/09/Immagine-WhatsApp-2025-09-24-ore-12.25.28_198034f0-1024x768.jpg",
    thumbnail_url: "https://www.museoarteurbana.it/wp-content/uploads/2025/09/Immagine-WhatsApp-2025-09-24-ore-12.25.28_198034f0-1024x768.jpg",
    image_alt: "Murale Campidoglius di Antonio Mascia in Piazza Moncenisio",
    location: { address: "Piazza Moncenisio 15, Torino", lat: 45.0841, lng: 7.6575 }
  },
  {
    id: "mau-freedom",
    title: "Freedom",
    title_it: "Freedom",
    artist: "Monica Garone",
    description: "A mural dedicated to the memory of Federica Fassola, between pop imagery, color and reflection on freedom.",
    description_it: "Un murale dedicato alla memoria di Federica Fassola, tra immaginario pop, colore e riflessione sulla libertà.",
    category: "hidden-art",
    type: "murale",
    neighborhood: "campidoglio",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    year: "2013",
    timeline_year: 2013,
    material_short: "Mural painting on panel",
    material_short_it: "Pittura murale su pannello",
    historical_context: "Freedom is a work by Monica Garone created in 2013 in via San Rocchetto, in the MAU path. The work was created to remember the craftswoman and restorer Federica Fassola.",
    historical_context_it: "Freedom è un'opera di Monica Garone realizzata nel 2013 in via San Rocchetto, nel percorso del MAU. L'opera è nata per ricordare l'artigiana e restauratrice Federica Fassola.",
    material_details: "The work uses a visual language close to neo-pop and street art. Bright colors, symbolic figures, and compact composition transform the mural panel into an immediately recognizable image in the urban space.",
    material_details_it: "L'opera utilizza un linguaggio visivo vicino al neo-pop e alla street art. Colori accesi, figure simboliche e composizione compatta trasformano il pannello murale in un'immagine immediatamente riconoscibile nello spazio urbano.",
    reuse_context: "Freedom shows how the MAU can also function as an emotional archive of the neighborhood. Individual memory is made public through urban art, becoming part of the collective narrative of Borgo Campidoglio.",
    reuse_context_it: "Freedom mostra come il MAU possa funzionare anche come archivio emotivo del quartiere. La memoria individuale viene resa pubblica attraverso l'arte urbana, diventando parte del racconto collettivo di Borgo Campidoglio.",
    image_url: "https://www.museoarteurbana.it/wp-content/uploads/2025/02/garrone-freedom-774x1024.jpg",
    thumbnail_url: "https://www.museoarteurbana.it/wp-content/uploads/2025/02/garrone-freedom-774x1024.jpg",
    image_alt: "Opera Freedom di Monica Garone in via San Rocchetto",
    location: { address: "Via San Rocchetto, Torino", lat: 45.0845, lng: 7.6570 }
  },
  {
    id: "mau-cor-lesu",
    title: "Cor lesu",
    title_it: "Cor lesu",
    artist: "Roberta Fanti",
    description: "A large red flower on a facade, where poetic image and inhabited space enter into relationship.",
    description_it: "Un grande fiore rosso su una facciata, in cui immagine poetica e spazio abitato entrano in relazione.",
    category: "hidden-art",
    type: "murale",
    neighborhood: "campidoglio",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    period_it: "Contemporaneo",
    year: "2009",
    timeline_year: 2009,
    material_short: "Mural painting",
    material_short_it: "Pittura murale",
    historical_context: "Cor lesu is a work by Roberta Fanti created in 2009 in via Locana 19, within the MAU path. The work is part of the artist's research, linked to symbolic images, floral elements, and reflections on the life-death cycle.",
    historical_context_it: "Cor lesu è un'opera di Roberta Fanti realizzata nel 2009 in via Locana 19, all'interno del percorso del MAU. L'opera si inserisce nella ricerca dell'autrice, legata alle immagini simboliche, agli elementi floreali e alla riflessione sul ciclo vita-morte.",
    material_details: "The mural depicts a large red flower that dialogues directly with the building's facade. The window of the house enters the visual composition, making the pictorial image and real architecture coexist.",
    material_details_it: "Il murale raffigura un grande fiore rosso che dialoga direttamente con la facciata dell'edificio. La finestra della casa entra nella composizione visiva, facendo coesistere immagine pittorica e architettura reale.",
    reuse_context: "Cor lesu makes evident one of the most interesting aspects of the MAU: the work is not separate from the building, but incorporates it. The inhabited house becomes a support and part of the image, transforming the private facade into public visual heritage.",
    reuse_context_it: "Cor lesu rende evidente uno degli aspetti più interessanti del MAU: l'opera non è separata dall'edificio, ma lo incorpora. La casa abitata diventa supporto e parte dell'immagine, trasformando la facciata privata in patrimonio visivo pubblico.",
    image_url: "https://www.museoarteurbana.it/wp-content/uploads/2023/12/fanti-1024x768.jpg",
    thumbnail_url: "https://www.museoarteurbana.it/wp-content/uploads/2023/12/fanti-1024x768.jpg",
    image_alt: "Murale Cor lesu di Roberta Fanti in via Locana",
    location: { address: "Via Locana 19, Torino", lat: 45.0841, lng: 7.6584 }
  }
];

export const ITINERARIES: Itinerary[] = [
  {
    id: "murales-campidoglio",
    route_id: "mau_campidoglio",
    title: "MAU: Borgo Campidoglio Murals",
    title_it: "MAU: I Murales di Borgo Campidoglio",
    description: "A walking path in the Museum of Urban Art of Borgo Campidoglio.",
    description_it: "Un percorso a piedi nel Museo d'Arte Urbana di Borgo Campidoglio.",
    narrative: "The MAU transforms Borgo Campidoglio into a widespread museum: the works are not collected in a building, but distributed on the facades, in the streets, and in the daily spaces of the neighborhood.",
    narrative_it: "Il MAU trasforma Borgo Campidoglio in un museo diffuso: le opere non sono raccolte in un edificio, ma distribuite sulle facciate, per le strade e negli spazi quotidiani del quartiere.",
    artworkIds: [
      "mau-freedom",
      "mau-assenza",
      "mau-campidoglius",
      "mau-cor-lesu"
    ],
    duration: "45 min",
    walkingTimes: ["2 min", "3 min", "3 min"],
    target: "Families, students and street art lovers",
    target_it: "Famiglie, studenti e amanti della street art",
    accessibility: "Good, paved but narrow streets",
    accessibility_it: "Buona, strade pavimentate ma strette",
    difficulty: "Easy",
    difficulty_it: "Facile",
    totalDistance: "1.0 km",
    routeType: "On foot",
    routeType_it: "A piedi",
    bestFor: "Photography, afternoon walks",
    bestFor_it: "Fotografia, passeggiate pomeridiane",
    warnings: "Be careful of local traffic in narrow streets",
    warnings_it: "Fare attenzione al traffico locale nelle vie strette"
  },
  {
    id: "torino-nascosta",
    route_id: "torino_nascosta_centro",
    title: "Unusual Turin",
    title_it: "Torino insolita",
    description: "From hidden details to urban legends: a walk through the lesser-known signs of Turin.",
    description_it: "Dai dettagli nascosti alle leggende urbane: una passeggiata tra i segni meno noti di Torino.",
    narrative: "Beyond the great Savoy avenues lies a city of bizarre details and urban legends. This path guides you to the discovery of those corners that often escape even the gaze of the most attentive Torinese: from the reversed David to the lucky finger of Colombo, from the palace with the piercing to the signs of war still visible in the walls of the center.",
    narrative_it: "Oltre i grandi corsi sabaudi si nasconde una città di dettagli bizzarri e leggende urbane. Questo percorso ti guida alla scoperta di quegli angoli che spesso sfuggono persino allo sguardo del torinese più attento: dal David rovesciato al dito portafortuna di Colombo, dal palazzo con il piercing ai segni della guerra ancora leggibili nelle mura del centro.",
    artworkIds: [
      "testa-michelangelo",
      "statua-emanuele-filiberto",
      "dito-colombo",
      "palazzo-piercing",
      "toro-muro",
      "palle-cannone"
    ],
    duration: "60 min",
    walkingTimes: ["5 min", "6 min", "4 min", "5 min", "1 min"],
    target: "Curious people, tourists looking for anecdotes, school groups",
    target_it: "Curiosi, turisti alla ricerca di aneddoti, scolaresche",
    accessibility: "Complete, entirely in pedestrian zone or wide sidewalks",
    accessibility_it: "Completa, interamente in zona pedonale o marciapiedi ampi",
    difficulty: "Easy",
    difficulty_it: "Facile",
    totalDistance: "1.8 km",
    routeType: "On foot",
    routeType_it: "A piedi",
    bestFor: "Hunters of urban stories and legends",
    bestFor_it: "Cacciatori di storie e leggende urbane",
    warnings: "Some passages under the porticoes can be crowded",
    warnings_it: "Alcuni passaggi sotto i portici possono essere affollati"
  },
  {
    id: "contemporaneo-centro",
    route_id: "contemporaneo_centro_mole",
    title: "Contemporary Path",
    title_it: "Percorso Contemporaneo",
    description: "A journey through contemporary installations that redefine the relationship between art and the historical city.",
    description_it: "Un viaggio tra le installazioni contemporanee che ridefiniscono il rapporto tra arte e città storica.",
    narrative: "This itinerary explores how contemporary artworks enter the historical fabric of Turin: hidden courtyards, urban facades, sound sculptures and architectural icons become part of a single path between Piazza San Carlo, the Quadrilatero and the Mole area.",
    narrative_it: "Questo itinerario esplora come le opere d'arte contemporanea entrino nel tessuto storico di Torino: cortili nascosti, facciate urbane, sculture sonore e icone architettoniche diventano parte di un unico percorso tra Piazza San Carlo, il Quadrilatero e la zona della Mole.",
    artworkIds: [
      "testa-michelangelo",
      "palazzo-piercing",
      "toro-muro",
      "l-eco",
      "mole-antonelliana"
    ],
    duration: "70 min",
    walkingTimes: ["8 min", "5 min", "12 min", "3 min"],
    target: "Contemporary art enthusiasts and esthetes",
    target_it: "Appassionati d'arte contemporanea ed esteti",
    accessibility: "Good, presence of historical paving with cobbles in paths",
    accessibility_it: "Buona, presenza di pavimentazione storica con ciottoli a tratti",
    difficulty: "Easy",
    difficulty_it: "Facile",
    totalDistance: "2.3 km",
    routeType: "On foot",
    routeType_it: "A piedi",
    bestFor: "Iconic views and impactful installations",
    bestFor_it: "Viste iconiche e installazioni d'impatto",
    warnings: "Entrance to some courtyards regulated by commercial opening hours",
    warnings_it: "L'ingresso ad alcuni cortili è regolato dagli orari di apertura commerciali"
  },
  {
    id: "torino-reale",
    route_id: "torino_reale_monumentale",
    title: "Torino Reale e Monumentale",
    title_it: "Torino Reale e Monumentale",
    description: "The great icons of Roman, Savoy and monumental Turin.",
    description_it: "Le grandi icone della Torino romana, sabauda e monumentale.",
    narrative: "A cultural itinerary through the symbolic places of Turin: from Palazzo Madama and the Royal Museums to the Chapel of the Shroud, Porta Palatina, the lucky ritual of Colombo's finger and the Mole Antonelliana.",
    narrative_it: "Un itinerario culturale tra i luoghi simbolo di Torino: da Palazzo Madama e i Musei Reali alla Cappella della Sindone, la Porta Palatina, il rito scaramantico del dito di Colombo e la Mole Antonelliana.",
    artworkIds: [
      "palazzo-madama",
      "musei-reali",
      "cappella-sindone",
      "porta-palatina",
      "dito-colombo",
      "mole-antonelliana"
    ],
    duration: "90 min",
    walkingTimes: ["3 min", "3 min", "6 min", "8 min", "12 min"],
    target: "History lovers, tourists on their first trip to Turin",
    target_it: "Amanti della storia, turisti al primo viaggio a Torino",
    accessibility: "Excellent, mostly pedestrianized and flat areas",
    accessibility_it: "Ottima, zone prevalentemente pedonalizzate e pianeggianti",
    difficulty: "Easy",
    difficulty_it: "Facile",
    totalDistance: "2.8 km",
    routeType: "On foot",
    routeType_it: "A piedi",
    bestFor: "Savoy history and key monuments",
    bestFor_it: "Storia sabauda e monumenti cardine",
    warnings: "Museums and internal chapels require a dedicated entrance ticket",
    warnings_it: "I musei e le cappelle interne richiedono un biglietto d'ingresso dedicato"
  },
  {
    id: "valentino-natura-memoria",
    route_id: "valentino_natura_memoria",
    title: "Valentino, Nature and Memory",
    title_it: "Valentino, Natura e Memoria",
    description: "An itinerary exploring the intersection of nature, memory and urban reuse.",
    description_it: "Un itinerario alla scoperta dell'intersezione tra natura, memoria e riuso urbano.",
    narrative: "This itinerary connects San Salvario and the Valentino area through works that speak about green architecture, recycled materials, romantic urban furniture and historical memory.",
    narrative_it: "Questo itinerario collega San Salvario e la zona del Valentino attraverso opere che parlano di architettura verde, materiali riciclati, arredo urbano romantico e memoria storica.",
    artworkIds: [
      "condominio-25-verde",
      "orso-bordalo",
      "panchina-innamorati",
      "sommergibile-provana"
    ],
    duration: "70 min",
    walkingTimes: ["10 min", "15 min", "8 min"],
    target: "Nature lovers, sustainable architecture and relaxing paths",
    target_it: "Amanti della natura, bioarchitettura sostenibile e percorsi relax",
    accessibility: "Good, paved and compact dirt park avenues",
    accessibility_it: "Buona, viali del parco asfaltati e sterrati compatti",
    difficulty: "Easy",
    difficulty_it: "Facile",
    totalDistance: "2.2 km",
    routeType: "On foot",
    routeType_it: "A piedi",
    bestFor: "Nature photography, outdoor relaxation",
    bestFor_it: "Fotografia naturalistica, relax all'aria aperta",
    warnings: "Be careful of mud or wet leaves in the avenues in case of rain",
    warnings_it: "Attenzione in caso di pioggia per fango o foglie bagnate nei viali"
  }
];

export const TIMELINE_ERAS: TimelineEra[] = [
  {
    id: "torino-romana",
    title: "Roman Turin",
    title_it: "Torino Romana",
    dateLabel: "I Century BC - IV Century AD",
    image_url: "https://www.tedxtorino.com/2017/wp-content/uploads/2017/09/Porta_Palatina_-_panoramio.jpg",
    image_alt: "Porta Palatina, fragments of Roman Turin",
    description: "Augusta Taurinorum is founded as a Roman colony. The city assumes the typical grid structure (the current Quadrilatero Romano) and is defended by walls and monumental gates.",
    description_it: "Augusta Taurinorum viene fondata come colonia romana. La città assume la tipica struttura a scacchiera (l'attuale Quadrilatero Romano) ed è difesa da mura e porte monumentali.",
    interpretation: "The matter of Roman Turin is brick: a solid structure that still defines the geometric rhythm of the historical center today.",
    interpretation_it: "La materia di Torino Romana è il mattone: una struttura solida che definisce ancora oggi il ritmo geometrico del centro storico.",
    artworkIds: ["porta-palatina", "palazzo-madama"]
  },
  {
    id: "torino-sabauda",
    title: "Savoy & Baroque Turin",
    title_it: "Torino Sabauda e Barocca",
    dateLabel: "XVI - XVIII Century",
    image_url: "https://museireali.beniculturali.it/wp-content/uploads/2023/06/banner-organizza-la-tua-visita-1-1280x663.jpg",
    image_alt: "The Royal Museums and Baroque architecture",
    description: "With the move of the capital from Chambéry to Turin (1563), the city transforms into a Baroque capital. Great architects like Guarini and Juvarra model the skyline with domes and royal palaces.",
    description_it: "Con il trasferimento della capitale da Chambéry a Torino (1563), la città si trasforma in capitale barocca. Grandi architetti come Guarini e Juvarra modellano lo skyline con cupole e palazzi reali.",
    interpretation: "Turin Baroque uses light and black marble to build a scenographic city, designed to celebrate Savoy power and dynastic devotion.",
    interpretation_it: "Il barocco torinese utilizza la luce e il marmo nero per costruire una città scenografica, pensata per celebrare il potere sabaudo e la devozione dinastica.",
    artworkIds: ["palazzo-madama", "musei-reali", "cappella-sindone"]
  },
  {
    id: "ottocento-monumentale",
    title: "19th Century & Risorgimento",
    title_it: "L'Ottocento e il Risorgimento",
    dateLabel: "XIX Century",
    image_url: "https://turinitalyguide.com/wp-content/uploads/2017/05/Mole-with-Turin-landscape-city-view.jpg",
    image_alt: "The Mole Antonelliana and 19th-century monuments",
    description: "Turin becomes the center of the Italian Risorgimento. Squares fill with celebratory statues and the city challenges gravity with the construction of the Mole Antonelliana.",
    description_it: "Torino diventa il centro del Risorgimento italiano. Le piazze si arricchiscono di statue celebrative e la città sfida la gravità con la costruzione della Mole Antonelliana.",
    interpretation: "The 19th century transforms Turin into an open-air monument, where bronze and masonry celebrate national unity and technological ambition.",
    interpretation_it: "L'Ottocento trasforma Torino in un monumento a cielo aperto, in cui il bronzo e la muratura celebrano l'unità nazionale e l'ambizione tecnologica.",
    artworkIds: ["statua-emanuele-filiberto", "mole-antonelliana"]
  },
  {
    id: "memorie-belliche",
    title: "Memories & Urban Traces",
    title_it: "Memorie e Tracce Urbane",
    dateLabel: "XVIII - XX Century",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2025/02/palle-cannone-palazzi-torino-633x400.jpg",
    image_alt: "Details of embedded cannonballs",
    description: "The wounds of war and popular rituals leave material traces on the city body. Embedded bullets and monuments eroded by the touch of passers-by become part of the invisible heritage.",
    description_it: "Le ferite della guerra e i rituali popolari lasciano tracce materiali sul corpo della città. Proiettili incastonati e monumenti erosi dal tocco dei passanti diventano parte del patrimonio invisibile.",
    interpretation: "These traces interrupt the monumental narrative to tell a story of resistance, superstition, and daily life.",
    interpretation_it: "Queste tracce interrompono la narrazione monumentale per raccontare una storia di resistenza, superstizione e vita quotidiana.",
    artworkIds: ["palle-cannone", "sommergibile-provana", "dito-colombo"]
  },
  {
    id: "torino-contemporanea",
    title: "Contemporary Turin",
    title_it: "Torino Contemporanea",
    dateLabel: "XXI Century",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2019/09/toro-esce-muro-torino.jpg",
    image_alt: "T'ORO by Richi Ferrero",
    description: "Post-industrial Turin opens up to new languages. Sound sculptures, installations that challenge facades, and bioarchitecture redefine the relationship between citizen and public space.",
    description_it: "La Torino post-industriale si apre a nuovi linguaggi. Sculture sonore, installazioni che sfidano le facciate e bioarchitettura ridefiniscono il rapporto tra cittadino e spazio pubblico.",
    interpretation: "Contemporary art acts as a poetic explosion inside the historical fabric, inviting us to look at the city with new and curious eyes.",
    interpretation_it: "L'arte contemporanea agisce come un'esplosione poetica all'interno del tessuto storico, invitandoci a guardare la città con occhi nuovi e curiosi.",
    artworkIds: ["testa-michelangelo", "l-eco", "toro-muro", "palazzo-piercing", "condominio-25-verde", "panchina-innamorati", "orso-bordalo"]
  },
  {
    id: "museo-urbano",
    title: "MAU: Museum of Urban Art",
    title_it: "MAU: Museo d'Arte Urbana",
    dateLabel: "Present",
    image_url: "https://www.museoarteurbana.it/wp-content/uploads/2023/12/fanti-1024x768.jpg",
    image_alt: "The murals of Borgo Campidoglio",
    description: "Borgo Campidoglio becomes an open-air museum where building facades host murals and installations. Art is no longer exclusive to museums, but lives in the neighborhood streets.",
    description_it: "Borgo Campidoglio diventa un museo a cielo aperto dove le facciate degli edifici ospitano parati, murali e installazioni. L'arte non è più esclusiva dei musei, ma vive nelle strade del quartiere.",
    interpretation: "The MAU demonstrates that urban heritage is alive and participatory: every wall can become a canvas for collective memory and daily beauty.",
    interpretation_it: "Il MAU dimostra che il patrimonio urbano è vivo e partecipativo: ogni muro può diventare tela di memoria collettiva e bellezza quotidiana.",
    artworkIds: ["mau-assenza", "mau-campidoglius", "mau-freedom", "mau-cor-lesu"]
  }
];
