import { Artwork, Itinerary, TimelineEra } from "./types";

export const ARTWORKS: Artwork[] = [
  // --- EXISTING UPDATED ---
   {
    id: "testa-michelangelo",
    title: "Testa rovesciata del David",
    artist: "Andrea Salvatori",
    description: "A contemporary reinterpretation of Michelangelo's David, hidden in the passage between Piazza San Carlo and Via Lagrange.",
    category: "contemporanea",
    type: "sculture",
    neighborhood: "centro",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    year: "2019",
    timeline_year: 2019,
    material_short: "Red earth",


    historical_context: "The Reversed Head of David is a contemporary work by Andrea Salvatori inspired by the famous head of Michelangelo's David. Located in the inner courtyard of Palazzo Villa, in the passage between Piazza San Carlo and Via Lagrange, it brings an absolute Renaissance reference into an everyday and almost hidden urban space. The work does not limit itself to quoting Michelangelo but reverses the image, transforming the classic model into a contemporary visual provocation.",
    material_details: "The sculpture is made of red earth and is hollow inside. Those who approach can observe an internal surface painted blue and dotted with stars, an element that recalls the full title of the work and the reference to Kant's phrase about the starry sky and the moral law. The contrast between the earthy external matter and the celestial interior makes the sculpture simultaneously physical, fragile, and symbolic.",
    reuse_context: "In the elegant context of Piazza San Carlo, the work introduces a poetic fracture: the classic is not exhibited as an untouchable model, but overturned, crossed, and transformed into an urban experience. The passerby thus discovers a Turin capable of hiding contemporary art inside historical and commercial places.",
    image_url: "https://www.vivatorino.it/wp-content/uploads/2021/05/testa-capovolta-david-1.jpg",
    thumbnail_url: "https://www.vivatorino.it/wp-content/uploads/2021/05/testa-capovolta-david-1.jpg",
    image_alt: "La scultura Testa rovesciata del David di Andrea Salvatori",
    model_url: "/models/29_04_2026.glb",
    
    location: { address: "Piazza San Carlo, 161, Torino", lat: 45.0679, lng: 7.6836 }
  },
  {
    id: "toro-muro",
    title: "T'ORO - Il Toro che esce dal muro",
    artist: "Richi Ferrero",
    description: "A bull with golden horns seems to break through the wall of a historical building in the Quadrilatero Romano.",
    category: "contemporanea",
    type: "installazione-urbana",
    neighborhood: "quadrilatero",
    visibility: "iconico",
    period: "Contemporaneo",
    timeline_year: 2018,
    material_short: "Mural installation",
    historical_context: "T'ORO is a contemporary work by Richi Ferrero located in via delle Orfane 20, in the Quadrilatero Romano. The work depicts a bull, symbol of the city of Turin, emerging from the wall of the Quadrato complex, an Urban Relais created in the context of the ancient convent of Sant'Agostino.",
    material_details: "The work uses the wall as an active surface: the bull does not simply appear applied to the facade but seems to break the wall and come out into the urban space. The golden horns function as a central visual element, attracting the eye and transforming an architectural corner into a dynamic scene.",
    reuse_context: "The bull breaking through the wall becomes a metaphor for the changing city. Inserted in an ancient and stratified neighborhood, the work creates a dialogue between the historical symbol of Turin and a contemporary language, suggesting that urban identity is not immobile but continues to re-emerge and transform.",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2019/09/toro-esce-muro-torino.jpg",
    thumbnail_url: "https://www.guidatorino.com/wp-content/uploads/2019/09/toro-esce-muro-torino.jpg",
    image_alt: "T'ORO, il toro che esce dal muro in via delle Orfane a Torino",
    location: { address: "Via delle Orfane, 20, Torino", lat: 45.0741, lng: 7.6816 }
  },
  {
    id: "l-eco",
    title: "Eco",
    artist: "Marc Didou",
    description: "A sound sculpture composed of two mirror heads reflecting on the theme of urban communication.",
    category: "contemporanea",
    type: "sculture",
    neighborhood: "centro",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    year: "2005",
    timeline_year: 2005,
    material_short: "Bronze, steel and concrete",
    historical_context: "Eco is a permanent urban art work created by Marc Didou and located in via Giuseppe Verdi, in the area of the Mole Antonelliana. It was conceived as part of the 'Cento Piazze per Torino' urban redevelopment competition, dedicated in this case to the theme of communication.",
    material_details: "The sculpture represents two human heads superimposed in a mirror-like way, built through stratigraphic sections that recall medical imaging techniques such as MRI. It is made of bronze, stainless steel, and concrete. Inside there is a water system: approaching the sculpture you can perceive the sound of water, invisible but present.",
    reuse_context: "Eco transforms a university and city passage into a place of listening. Instead of communicating only through visual form, the work forces the visitor to slow down and use hearing as well. The theme of communication thus becomes a physical, urban, and sensory experience.",
    thumbnail_url: "https://www.museotorino.it/images/74/0c/24/d4/740c24d4988c44edaeb8c41bda1b6282-3.jpg",
    image_alt: "La scultura Eco di Marc Didou in via Giuseppe Verdi a Torino",
    location: { address: "Via Giuseppe Verdi, 39, Torino", lat: 45.0679, lng: 7.6937 }
  },
  {
    id: "mole-antonelliana",
    title: "Mole Antonelliana",
    artist: "Alessandro Antonelli",
    description: "The architectural symbol of Turin, born as a synagogue and today home to the National Museum of Cinema.",
    category: "monumento",
    type: "architettura",
    neighborhood: "vanchiglia",
    visibility: "iconico",
    period: "XIX Secolo",
    year: "1863-1889",
    timeline_year: 1863,
    material_short: "Masonry, stone and metal structure",
    historical_context: "The Mole Antonelliana was designed by Alessandro Antonelli and started in 1863 as a new synagogue for the Turin Jewish community. It was later purchased by the City of Turin and destined as a monument to national unity. Completed in 1889, it soon became the city's main architectural symbol.",
    material_details: "The Mole is famous for its exceptional vertical development and for its originally masonry structure. At approximately 167.5 meters high, it was one of the tallest masonry buildings in Europe at the time. The dome, the small temple, and the spire create an immediately recognizable urban profile.",
    reuse_context: "The Mole is an emblematic case of functional and symbolic transformation: born as a religious building, it became a civic monument and is today the seat of the National Museum of Cinema. Its value lies not only in its form, but in its ability to change function while maintaining a strong centrality in the Turin imagination.",
    image_url: "https://turinitalyguide.com/wp-content/uploads/2017/05/Mole-with-Turin-landscape-city-view.jpg",
    thumbnail_url: "https://turinitalyguide.com/wp-content/uploads/2014/01/Mole-768x1024.jpg",
    image_alt: "Mole antonelliana Simbolo di torino",

    before_image_url: "https://www.atlanteditorino.it/approfondimenti/img/MoleTifone.gif",
    after_image_url: "https://turinitalyguide.com/wp-content/uploads/2017/05/Mole-with-Turin-landscape-city-view.jpg",
    before_image_alt: "Immagine storica della Mole Antonelliana",
    after_image_alt: "Vista attuale della Mole Antonelliana",
    location: { address: "Via Montebello, 20, Torino", lat: 45.0689, lng: 7.6931 }
  },
  {
    id: "statua-emanuele-filiberto",
    title: "Monumento a Emanuele Filiberto (Caval ëd Bronz)",
    artist: "Carlo Marochetti",
    description: "The famous equestrian statue in Piazza San Carlo, dedicated to the duke who moved the Savoy capital to Turin.",
    category: "storica",
    type: "sculture",
    neighborhood: "centro",
    visibility: "iconico",
    period: "XIX Secolo",
    year: "1838",
    timeline_year: 1838,
    material_short: "Bronze and marble",
    historical_context: "The equestrian monument to Emanuele Filiberto of Savoy, known as Caval ëd Bronz, was created by Carlo Marochetti and inaugurated in 1838 in the center of Piazza San Carlo. It celebrates the duke who in 1563 moved the capital of the duchy from Chambéry to Turin, marking a fundamental turning point in the political history of the city.",
    material_details: "The bronze statue shows Emanuele Filiberto on horseback in a solemn and controlled pose. The base features reliefs related to the Battle of St. Quentin and the Treaty of Cateau-Cambrésis. The bronze gives the work a stable monumental presence, reinforced by its central position in the square.",
    reuse_context: "The Caval ëd Bronz transforms Piazza San Carlo into a political and urban scene. Today it functions not only as a dynastic monument, but as a point of orientation, meeting, and collective recognition in the heart of historical Turin.",
    image_url: "https://c7.alamy.com/compit/3cf9wka/monumento-a-emanuele-filiberto-caval-d-brons-3cf9wka.jpg",
    thumbnail_url: "https://torinostoria.com/wp19/wp-content/uploads/2019/11/PIAZZA-SAN-CARLO_2019-2354.jpg",
    image_alt: "statua emanuele filiberto",
    location: { address: "Piazza San Carlo, Torino", lat: 45.0677, lng: 7.6827 }
  },
  {
    id: "porta-palatina",
    title: "Porta Palatina",
    artist: "Epoca romana",
    description: "One of the best-preserved Roman city gates, material testimony of ancient Turin.",
    category: "monumento",
    type: "architettura",
    neighborhood: "centro",
    visibility: "iconico",
    period: "Epoca romana",
    year: "I Secolo",
    timeline_year: 1,
    material_short: "Brick and Roman masonry",
    historical_context: "The Porta Palatina is one of the main remains of Roman Turin. It was a city gate of Augusta Taurinorum and represented a monumental access point to the city space. Over the centuries it lost its original function, was transformed and reused, until it was progressively isolated and restored as an archaeological monument.",
    material_details: "The structure preserves two tall side towers, a central body with carriage and pedestrian arches, and brick masonry with decorative architectural elements. The material of the gate still shows the defensive function and access control, but also the traces of subsequent transformations.",
    reuse_context: "Today the Porta Palatina no longer serves to defend or control the city, but to make its Roman origin legible. Inserted in the archaeological park, it becomes a narrative threshold: the visitor ideally crosses the passage between contemporary Turin and Augusta Taurinorum.",
    image_url: "https://www.tedxtorino.com/2017/wp-content/uploads/2017/09/Porta_Palatina_-_panoramio.jpg",
    thumbnail_url: "https://www.tedxtorino.com/2017/wp-content/uploads/2017/09/Porta_Palatina_-_panoramio.jpg",
    image_alt: "Porta palatina",

    before_image_url: "https://mole24.it/wp-content/uploads/2020/11/1000_Ricostruzione-1-1024x1016.jpg",
    after_image_url: "https://www.tedxtorino.com/2017/wp-content/uploads/2017/09/Porta_Palatina_-_panoramio.jpg",
    before_image_alt: "Immagine storica della Mole Antonelliana",
    after_image_alt: "Vista attuale della Mole Antonelliana",

    location: { address: "Piazza Cesare Augusto, Torino", lat: 45.0750, lng: 7.6847 }
  },
  {
    id: "palazzo-piercing",
    title: "Baci Urbani (Palazzo con il Piercing)",
    artist: "Corrado Levi e Cliostraat",
    description: "A large metal piercing pierces the corner of an eighteenth-century palace in the center of Turin.",
    category: "hidden-art",
    type: "installazione-urbana",
    neighborhood: "centro",
    visibility: "poco-conosciuto",
    period: "Postmoderno",
    year: "1996",
    timeline_year: 1996,
    material_short: "Steel and paint",
    historical_context: "Urban Kisses, known as the Palace with the Piercing, is a contemporary installation created by Corrado Levi in collaboration with the group Cliostraat. Born as a temporary intervention, it remained on the corner of the building in via Palazzo di Città 19, near Piazza Castello, becoming one of the most recognizable urban curiosities in the center.",
    material_details: "The work consists of a large metal ring applied to the corner of the fourth floor of the building. On the sides appear two droplets of red and blue color, interpreted as a reference to the double soul of the city: the popular one and the noble one. The historical facade is treated as an urban skin crossed by a contemporary sign.",
    reuse_context: "The piercing does not erase the architectural tradition but inserts itself in a provocative way. The work makes visible the dialogue between Savoy Turin and contemporary urban languages, transforming a facade detail into a small social narrative.",
    image_url: "https://www.tastingtheworld.it/wp-content/uploads/2013/01/piercing-urbano-torino-baci-urbani.jpg",
    thumbnail_url: "https://www.tastingtheworld.it/wp-content/uploads/2013/01/piercing-urbano-torino-baci-urbani.jpg",
    image_alt: "Palazzo piercing",
    location: { address: "Via Palazzo di Città, 19, Torino", lat: 45.0716, lng: 7.6811 }
  },
  {
    id: "palle-cannone",
    title: "Le Palle di Cannone dell'Assedio",
    artist: "Memoria degli assedi di Torino",
    description: "Bullets embedded in the facades of the historic center recall the sieges and bombings suffered by the city.",
    category: "hidden-art",
    type: "sculture",
    neighborhood: "quadrilatero",
    visibility: "molto-nascosto",
    period: "XVIII Secolo",
    year: "1706 / 1799",
    timeline_year: 1706,
    material_short: "Iron and masonry",
    historical_context: "The cannonballs visible on some Turin facades are testimonies of the sieges and bombings suffered by the city, particularly in 1706 and 1799. Some projectiles were intentionally walled into the buildings to preserve the memory of those critical moments and the resistance of the city.",
    material_details: "The material value of the work lies in the contrast between the iron of the projectiles and the stone or plaster of the facades. These are not decorations, but war fragments transformed into permanent traces. The material preserves the trauma instead of erasing it.",
    reuse_context: "These cannonballs transform the city walls into a widespread archive. The visitor encounters the memory of war not inside a museum, but in the daily surfaces of buildings, where history remains embedded in the urban fabric.",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2025/02/palle-cannone-palazzi-torino-633x400.jpg",
    thumbnail_url: "https://www.guidatorino.com/wp-content/uploads/2025/02/palle-cannone-palazzi-torino-633x400.jpg",
    image_alt: "Palla di cannone incastonata in una facciata storica di Torino",
    location: { address: "Via delle Orfane, 20, Torino", lat: 45.0741, lng: 7.6816 }
  },
  {
    id: "orso-bordalo",
    title: "The Big Bear",
    artist: "Bordalo II",
    description: "A huge bear built with waste materials observes passers-by from the side wall of the Colosseo Theater.",
    category: "hidden-art",
    type: "murale",
    neighborhood: "san-salvario",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    year: "2016",
    timeline_year: 2016,
    material_short: "Trash and recycled materials",
    historical_context: "The Big Bear is a work by the Portuguese artist Bordalo II, created in 2016 on the side wall of the Teatro Colosseo, in via Giorgio Bidone, in the San Salvario district. It is part of the Big Trash Animals series, with which the artist represents monumental animals using waste and scrap materials.",
    material_details: "The bear is composed of recovered objects such as bicycle frames, sheets, bins, and other discarded urban materials. The three-dimensional assembly technique makes the work a cross between a sculpture, a mural, and an environmental installation. The material is not neutral: waste is an essential part of the message.",
    reuse_context: "The work transforms the theater facade into an ecological manifesto. Representing an animal with the waste produced by urban society creates a short circuit between nature and consumption, making the wall a place of environmental denunciation and visual regeneration.",
    image_url: "https://c7.alamy.com/compit/2ap2d9p/l-orso-opera-dell-artista-di-strada-portoghese-bordalo-ii-sulla-parete-laterale-del-teatro-colosseo-nel-quartiere-di-san-salvario-torino-piemonte-italia-2ap2d9p.jpg",
    thumbnail_url: "https://streetartutopia.com/wp-content/uploads/2016/12/Street-Art-by-Bordalo-II-in-Turin-Italy-at-teartrocolosseo-Bear.jpg",
    image_alt: "The Big Bear",
    location: { address: "Via Giorgio Bidone, 30, Torino", lat: 45.0565, lng: 7.6815 }
  },
  {
    id: "dito-colombo",
    title: "Il Dito di Colombo",
    artist: "Dino Somà",
    description: "Columbus's bronze pinky finger, worn down by passers-by, has become a Turin good luck ritual.",
    category: "hidden-art",
    type: "sculture",
    neighborhood: "centro",
    visibility: "iconico",
    period: "XX Secolo",
    year: "1923",
    timeline_year: 1923,
    material_short: "Bronze",
    historical_context: "Columbus's Finger is part of a bronze bas-relief medallion dedicated to Christopher Columbus, located under the porticoes of the Prefecture in Piazza Castello, near the Royal Library. It was created by Dino Somà and inaugurated in 1923 to commemorate the participation of Italian emigrants in Latin America in the First World War.",
    material_details: "The most evident detail is the pinky finger of Columbus's hand, much shinier than the rest of the bronze due to constant rubbing by passers-by. The consumption of the surface has become an integral part of the work, making visible the physical relationship between monument and public.",
    reuse_context: "Popular tradition has it that touching the finger brings good luck, especially to students before exams. The monument has thus taken on a second life: from historical memory it has become a daily gesture, urban superstition, and collective ritual.",
    image_url: "https://offloadmedia.feverup.com/torinosegreta.com/wp-content/uploads/2022/03/24034239/dito-colombo-torino-1024x683.png",
    thumbnail_url: "https://www.cristoforocolombo.com/wp-content/uploads/2016/12/COLOMBO-ARTE-mignolo-Cristoforo-e-compasso-DOC-DOC-DOC.jpg",
    image_alt: "Dito di colombo",
    location: { address: "Piazza Castello, Torino", lat: 45.0712, lng: 7.6845 }
  },
  {
    id: "panchina-innamorati",
    title: "La Panchina degli Innamorati",
    artist: "Rodolfo Marasciuolo",
    description: "Two anthropomorphic street lamps embrace on a bench in the Rocky Garden of the Valentino.",
    category: "hidden-art",
    type: "installazione-urbana",
    neighborhood: "borgo-po",
    visibility: "iconico",
    period: "Contemporaneo",
    timeline_year: 2010,
    material_short: "Iron and street furniture",
    historical_context: "The Lovers' Bench, also called Innamorati Lamps, is located in the Garden Rocky area of the Parco del Valentino, near the Medieval Village. The work was created by Rodolfo Marasciuolo, a gardener-artist known for enriching Turin's green spaces with poetic installations.",
    material_details: "The work transforms ordinary street furniture elements into affective figures. Two street lamps are represented as characters sitting on a bench, one of which seems to rest its head on the other's shoulder. Iron, a normally cold and functional material, becomes a vehicle for tenderness and complicity.",
    reuse_context: "In the quiet landscape of the Valentino, the bench becomes a place of pause and interpretation. It does not tell a great historical event, but enhances an everyday and relational dimension of the city: love, the pause, the simple shared gesture in public space.",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2022/01/panchina-innamorati-torino-633x400.jpg",
    thumbnail_url: "https://i.pinimg.com/736x/ef/4c/c5/ef4cc527c80d1bdda5509bfbbf6b19bf.jpg",
    image_alt: "La Panchina degli Innamorati nel Giardino Roccioso del Valentino",
    location: { address: "Giardino Roccioso, Parco del Valentino, Torino", lat: 45.0560, lng: 7.6840 }
  },
  {
    id: "condominio-25-verde",
    title: "Condominio 25 Verde",
    artist: "Luciano Pia",
    description: "An eco-sustainable residential building that integrates architecture, vegetation and urban life.",
    category: "contemporanea",
    type: "architettura",
    neighborhood: "san-salvario",
    visibility: "poco-conosciuto",
    period: "Contemporaneo",
    year: "2010-2013",
    timeline_year: 2010,
    material_short: "Steel, wood and vegetation",
    historical_context: "The 25 Verde Condominium is a residential building designed by Luciano Pia in via Gabriele Chiabrera 25, in the San Salvario district. Built between 2010 and 2013 and inaugurated in 2014, it represents one of the most well-known Turin cases of eco-sustainable bioarchitecture.",
    material_details: "The building combines steel, wood, and vegetation. The metallic structures recall trunks and branches, the wooden cladding evokes bark, and the presence of trees, green terraces, and roof gardens changes the appearance of the building over time. Vegetation is not simple decoration, but part of the environmental behavior of the architecture.",
    reuse_context: "25 Verde proposes a different idea of urban living: it does not separate home and nature but overlaps them. In the dense fabric of San Salvario, the building becomes an experiment in coexistence between residence, microclimate, vegetation, and city landscape.",
    image_url: "https://www.secondamanoitalia.it/wp-content/uploads/2021/12/condominio-25-verde-1024x683.jpg",
    thumbnail_url: "https://www.openhousetorino.it/wp-content/gallery/25-verde/thumbs/thumbs_25-verde%40Fabrizio-Mauro_1.jpg",
    image_alt: "Palla di cannone incastonata in una facciata storica di Torino",

    //before_image_url: "https://link-immagine-storica.jpg",
    //after_image_url: "https://link-immagine-attuale.jpg",
    before_image_alt: "Immagine storica della Mole Antonelliana",
    after_image_alt: "Vista attuale della Mole Antonelliana",

    location: { address: "Via Gabriele Chiabrera, 25, Torino", lat: 45.0454, lng: 7.6800 }
  },
  {
    id: "sommergibile-provana",
    title: "Sommergibile Andrea Provana",
    artist: "Cantieri Fiat San Giorgio",
    description: "A section of a World War I submarine preserved in the Valentino Park.",
    category: "monumento",
    type: "installazione-urbana",
    neighborhood: "borgo-po",
    visibility: "poco-conosciuto",
    period: "Prima Guerra Mondiale",
    year: "1915-1928",
    timeline_year: 1915,
    material_short: "Naval steel",
    historical_context: "The Andrea Provana submarine was built in 1915 in the Fiat San Giorgio shipyards of La Spezia and launched in 1918 by the Royal Navy. It did not participate in war actions during the First World War but was used for training activities. Its central section was brought to Turin for the 1928 Exhibition and subsequently placed in the Valentino Park.",
    material_details: "Not the entire submarine is preserved in Turin, but the central section with conning tower and cannons. The metallic material, thought for the marine and military environment, appears strongly clinical in the green of the park and along the banks of the Po. Precisely this contrast makes the find particularly recognizable.",
    reuse_context: "The Provana is interesting because it completely changes context: from a naval and military machine it becomes an urban find and visitable memory. In the Valentino, war technology loses its original function and is transformed into a historical document accessible to the public.",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2019/08/sommergibile-torino-provana-633x400.jpg ",
    thumbnail_url: "https://www.guidatorino.com/wp-content/uploads/2019/08/sommergibile-torino-provana-633x400.jpg",
    image_alt: "Il sommergibile Andrea Provana nel Parco del Valentino",
    location: { address: "Viale Marinai d'Italia, 1, Torino", lat: 45.0535, lng: 7.6855 }
  },
  {
    id: "palazzo-madama",
    title: "Palazzo Madama",
    artist: "Filippo Juvarra e trasformazioni precedenti",
    description: "A stratified building that summarizes two thousand years of Turin history, from the Roman gate to the city museum.",
    category: "monumento",
    type: "architettura",
    neighborhood: "centro",
    visibility: "iconico",
    period: "Romano / Medievale / Barocco",
    year: "I Secolo - XVIII Secolo",
     timeline_year: 1718,
    material_short: "Brick, stone and historical masonry",
    historical_context: "Palazzo Madama is one of the most stratified buildings in Turin. Its history starts from the Roman gate incorporated into the structure, goes through the medieval phase of the castle and arrives at the Baroque and court transformation, with the large facade designed by Filippo Juvarra. Today it houses the Civic Museum of Ancient Art.",
    material_details: "The palace shows materials, forms, and languages belonging to different eras: Roman remains, medieval structures, towers, representation rooms, and Baroque facade. Its architectural material is a palimpsest: it does not erase previous phases, but makes them legible in the same building body.",
    reuse_context: "Palazzo Madama is a synthesis of the city itself. From defensive structure to residence, from place of power to museum, it demonstrates how urban heritage can change function without losing historical depth. Its current identity arises precisely from the overlap of uses and meanings.",
    image_url: "/Palazzo-Madama-Front-Photo.webp",
    thumbnail_url: "/Palazzo-Madama-Front-Photo.webp",
    image_alt: "Palazzo Madama in Piazza Castello a Torino",

    before_image_url: "https://www.museotorino.it/images/71/2a/a0/cd/712aa0cd3d594827b27191b6151e48f4-1.jpg",
    after_image_url: "/Palazzo-Madama-Front-Photo.webp",
    before_image_alt: "Immagine storica di palazzo Madama",
    after_image_alt: "Vista attuale di palazzo Madama",

    location: { address: "Piazza Castello, Torino", lat: 45.0708, lng: 7.6855 }
  },
  {
    id: "cappella-sindone",
    title: "Cappella della Sacra Sindone",
    artist: "Guarino Guarini",
    description: "A Baroque masterpiece designed to house the Shroud, marked by the 1997 fire and the long restoration.",
    category: "monumento",
    type: "architettura",
    neighborhood: "centro",
    visibility: "iconico",
    period: "Barocco",
    year: "1668-1694",
    timeline_year: 1668,
    material_short: "Black Frabosa marble",
    historical_context: "The Chapel of the Holy Shroud was designed by Guarino Guarini between the Cathedral and the Royal Palace to house the Shroud. It is one of the masterpieces of European Baroque and one of the most significant places in Savoy Turin. After the serious fire of 1997, it underwent a long restoration and reopened to the public in 2018.",
    material_details: "The chapel is characterized by the use of black marble, a complex geometric structure, and a dome built as an optical and symbolic machine. The material also preserves the memory of the damage: the restoration had to deal with fractures, high temperatures, replacements, and recoveries of stone elements.",
    reuse_context: "Today the Shroud Chapel tells not only of religious devotion and Savoy power, but also of the fragility of heritage. Its contemporary value lies in the relationship between ruin, restoration, and public restitution: the monument survived thanks to new material care and interpretation.",
    image_url: "https://cosediviaggio.it/wp-content/uploads/2020/11/duomo-di-torino.jpg",
    thumbnail_url: "https://www.guidatorino.com/wp-content/uploads/2018/09/cappella-sindone-torino-7-633x400.jpg",
    image_alt: "La Cappella della Sacra Sindone a Torino",
    before_image_url: "https://upload.wikimedia.org/wikipedia/it/8/89/Incendio_Sindone_1.jpg",
    after_image_url: "https://cosediviaggio.it/wp-content/uploads/2020/11/duomo-di-torino.jpg",
    before_image_alt: "Immagine storica della cappella-sindone",
    after_image_alt: "Vista attuale del duomo",

    location: { address: "Piazza Duomo, Torino", lat: 45.0732, lng: 7.6859 }
  },
  {
    id: "musei-reali",
    title: "Musei Reali",
    artist: "Vari",
    description: "A large museum complex that collects the political, artistic and dynastic memory of Savoy Turin.",
    category: "monumento",
    type: "architettura",
    neighborhood: "centro",
    visibility: "iconico",
    period: "XVI-XIX Secolo",
    year: "1563",
    timeline_year: 1563,
    material_short: "Stone, marble, historical collections",
    historical_context: "The Royal Museums bring together some of the fundamental places of Savoy and city history, including the Royal Palace, Royal Armory, Shroud Chapel, Sabauda Gallery, Museum of Antiquity, Royal Library, and Royal Gardens. The complex is located in the heart of the ancient center and represents the transformation of the seat of power into public heritage.",
    material_details: "The material value of the complex lies in the variety of its environments and collections: representation rooms, weapons, works of art, archaeological finds, books, gardens, and monumental architecture. Each section preserves different materials, but all contribute to the construction of the historical image of the Savoy dynasty.",
    reuse_context: "The ancient seat of monarchic power is today a museum hub open to citizens and visitors. What once represented authority and selective access is reinterpreted as a space for knowledge, visiting, and cultural sharing.",
    image_url: "https://museireali.beniculturali.it/wp-content/uploads/2023/06/banner-organizza-la-tua-visita-1-1280x663.jpg",
    thumbnail_url: "https://scorcidimondo.it/wp-content/uploads/2022/02/PSX_20220209_103924-scaled.jpg",
    image_alt: "palazzo reale di Torino",
    location: { address: "Piazzetta Reale, 1, Torino", lat: 45.0725, lng: 7.6860 }
  },
  {
  id: "mau-assenza",
  title: "L’assenza",
  artist: "Nice & the fox + Vito Navolio",
  description: "A mural that addresses the theme of memory and loss through an intense portrait and vital colors.",
  category: "hidden-art",
  type: "murale",
  neighborhood: "campidoglio",
  visibility: "poco-conosciuto",
  period: "Contemporaneo",
  year: "2023",
  timeline_year: 2023,
  material_short: "Mural painting",
  historical_context: "L'assenza is a work by MAU created by Nice & the fox along with Vito Navolio in via Nicola Fabrizi 21. The work belongs to the recent phase of the Museum of Urban Art, confirming the vitality of the Borgo Campidoglio project as a widespread and updatable museum over time.",
  material_details: "The mural occupies the wall of a corner building and depicts a male portrait framed by brilliant chromatic fields and stylized vegetable motifs. The contrast between realistic face and abstract background produces a strong visual impact.",
  reuse_context: "The work transforms an urban facade into a space of emotional memory. The theme of absence is made public and shared, while the colors and natural elements suggest a tension towards vitality and hope.",
  
  image_url: "https://civico20-news.it/wp-content/uploads/2024/06/Diapositiva3-17.jpeg",
  thumbnail_url: "https://civico20-news.it/wp-content/uploads/2024/06/Diapositiva3-17.jpeg",
  image_alt: "Murale Campidoglius di Antonio Mascia in Piazza Moncenisio",
  
  
  location: { address: "Via Nicola Fabrizi 21, Torino", lat: 45.0839, lng: 7.6568 }
},
{
  id: "mau-campidoglius",
  title: "Campidoglius",
  artist: "Antonio Mascia",
  description: "A large red sea creature animates a wall in Piazza Moncenisio, transforming the neighborhood into a fanstastic tale.",
  category: "hidden-art",
  type: "murale",
  neighborhood: "campidoglio",
  visibility: "poco-conosciuto",
  period: "Contemporaneo",
  year: "2001 / remake 2024",
  timeline_year: 2001,
  material_short: "Mural painting",
  historical_context: "Campidoglius is a work by Antonio Mascia created in the context of the MAU in Piazza Moncenisio 15. The original work dates back to 2001 and was reinterpreted in 2024, as part of the maintenance and renewal process of the urban museum's works.",
  material_details: "The mural depicts a large red sea creature, a female figure with a diving mask, fish, and aquatic animals. The 2024 version also introduces an elderly reader sitting, observing and taking notes. The Campidoglio lettering explicitly links the work to the neighborhood.",
  reuse_context: "Campidoglius transforms the wall into a narrative and fantastic device. The 2024 remake shows well how the MAU is not a stationary archive, but a living urban heritage, subject to care, updating, and reinterpretation.",
  image_url: "https://www.museoarteurbana.it/wp-content/uploads/2025/09/Immagine-WhatsApp-2025-09-24-ore-12.25.28_198034f0-1024x768.jpg",
  thumbnail_url: "https://www.museoarteurbana.it/wp-content/uploads/2025/09/Immagine-WhatsApp-2025-09-24-ore-12.25.28_198034f0-1024x768.jpg",
  image_alt: "Murale Campidoglius di Antonio Mascia in Piazza Moncenisio",
  location: { address: "Piazza Moncenisio 15, Torino", lat: 45.0841, lng: 7.6575 }
},
{
  id: "mau-freedom",
  title: "Freedom",
  artist: "Monica Garone",
  description: "A mural dedicated to the memory of Federica Fassola, between pop imagery, color and reflection on freedom.",
  category: "hidden-art",
  type: "murale",
  neighborhood: "campidoglio",
  visibility: "poco-conosciuto",
  period: "Contemporaneo",
  year: "2013",
  timeline_year: 2013,
  material_short: "Mural painting on panel",
  historical_context: "Freedom is a work by Monica Garone created in 2013 in via San Rocchetto, in the MAU path. The work was created to remember the craftswoman and restorer Federica Fassola.",
  material_details: "The work uses a visual language close to neo-pop and street art. Bright colors, symbolic figures, and compact composition transform the mural panel into an immediately recognizable image in the urban space.",
  reuse_context: "Freedom shows how the MAU can also function as an emotional archive of the neighborhood. Individual memory is made public through urban art, becoming part of the collective narrative of Borgo Campidoglio.",
  image_url: "https://www.museoarteurbana.it/wp-content/uploads/2025/02/garrone-freedom-774x1024.jpg",
  thumbnail_url: "https://www.museoarteurbana.it/wp-content/uploads/2025/02/garrone-freedom-774x1024.jpg",
  image_alt: "Opera Freedom di Monica Garone in via San Rocchetto",
  location: { address: "Via San Rocchetto, Torino", lat: 45.0845, lng: 7.6570 }
},
{
  id: "mau-cor-lesu",
  title: "Cor lesu",
  artist: "Roberta Fanti",
  description: "A large red flower on a facade, where poetic image and inhabited space enter into relationship.",
  category: "hidden-art",
  type: "murale",
  neighborhood: "campidoglio",
  visibility: "poco-conosciuto",
  period: "Contemporaneo",
  year: "2009",
  timeline_year: 2009,
  material_short: "Mural painting",
  historical_context: "Cor lesu is a work by Roberta Fanti created in 2009 in via Locana 19, within the MAU path. The work is part of the artist's research, linked to symbolic images, floral elements, and reflections on the life-death cycle.",
  material_details: "The mural depicts a large red flower that dialogues directly with the building's facade. The window of the house enters the visual composition, making the pictorial image and real architecture coexist.",
  reuse_context: "Cor lesu makes evident one of the most interesting aspects of the MAU: the work is not separate from the building, but incorporates it. The inhabited house becomes a support and part of the image, transforming the private facade into public visual heritage.",
  image_url: "https://www.museoarteurbana.it/wp-content/uploads/2023/12/fanti-1024x768.jpg",
  thumbnail_url: "https://www.museoarteurbana.it/wp-content/uploads/2023/12/fanti-1024x768.jpg",
  image_alt: "Murale Cor lesu di Roberta Fanti in via Locana",
  location: { address: "Via Locana 19, Torino", lat: 45.0841, lng: 7.6584 }
}
];

export const ITINERARIES: Itinerary[] = [

  {
  id: "murales-campidoglio",
  title: "MAU: Borgo Campidoglio Murals",
  description: "A walking path in the Museum of Urban Art of Borgo Campidoglio, between painted facades, neighborhood memory, and contemporary public art.",
  narrative: "The MAU transforms Borgo Campidoglio into a widespread museum: the works are not collected in a building, but distributed on the facades, in the streets, and in the daily spaces of the neighborhood. This itinerary follows four official and verifiable murals, showing how urban art can become a tool for memory, redevelopment, and participation. Each stop interprets the wall not as a simple support, but as a living surface in dialogue with inhabitants, passers-by, and local history.",
  artworkIds: [
    "mau-freedom",
    "mau-assenza",
    "mau-campidoglius",
    "mau-cor-lesu"
  ],
  duration: "45 min",
  walkingTimes: ["2 min", "3 min", "3 min"]
},
  {
    id: "torino-nascosta",
    title: "Unusual Turin",
    description: "From cannonballs to piercing: a tour through the quirks and lesser-known secrets of the city.",
    narrative: "Beyond the great Savoy avenues lies a city of bizarre details and urban legends. This path guides you to the discovery of those corners that often escape even the gaze of the most attentive Torinese: from the 'palace with the piercing' to the signs of war still visible in the walls of the center.",
    artworkIds: ["palazzo-piercing", "palle-cannone", "orso-bordalo", "dito-colombo"],
    duration: "2 hours",
    walkingTimes: ["15 min", "12 min", "10 min"]
  },
  {
    id: "contemporaneo-centro",
    title: "Contemporary Path",
    description: "A journey through the installations that have redefined the face of historical squares in the last twenty years.",
    artworkIds: ["testa-michelangelo", "toro-muro", "l-eco", "condominio-25-verde"],
    duration: "2 hours"
  },
  {
    id: "torino-reale",
    title: "Torino of Monuments",
    description: "The great icons of the Savoy city, between architectural symbols and equestrian sculptures.",
    artworkIds: ["mole-antonelliana", "statua-emanuele-filiberto", "porta-palatina", "palazzo-madama", "cappella-sindone"],
    duration: "3 hours"
  }
];

export const TIMELINE_ERAS: TimelineEra[] = [
  {
    id: "torino-romana",
    title: "Roman Turin",
    dateLabel: "I Century BC - IV Century AD",
    image_url: "https://www.tedxtorino.com/2017/wp-content/uploads/2017/09/Porta_Palatina_-_panoramio.jpg",
    image_alt: "Porta Palatina, fragments of Roman Turin",
    description: "Augusta Taurinorum is founded as a Roman colony. The city assumes the typical grid structure (the current Quadrilatero Romano) and is defended by walls and monumental gates.",
    interpretation: "The matter of Roman Turin is brick: a solid structure that still defines the geometric rhythm of the historical center today.",
    artworkIds: ["porta-palatina", "palazzo-madama"]
  },
  {
    id: "torino-sabauda",
    title: "Savoy & Baroque Turin",
    dateLabel: "XVI - XVIII Century",
    image_url: "https://museireali.beniculturali.it/wp-content/uploads/2023/06/banner-organizza-la-tua-visita-1-1280x663.jpg",
    image_alt: "The Royal Museums and Baroque architecture",
    description: "With the move of the capital from Chambéry to Turin (1563), the city transforms into a Baroque capital. Great architects like Guarini and Juvarra model the skyline with domes and royal palaces.",
    interpretation: "Turin Baroque uses light and black marble to build a scenographic city, designed to celebrate Savoy power and dynastic devotion.",
    artworkIds: ["palazzo-madama", "musei-reali", "cappella-sindone"]
  },
  {
    id: "ottocento-monumentale",
    title: "19th Century & Risorgimento",
    dateLabel: "XIX Century",
    image_url: "https://turinitalyguide.com/wp-content/uploads/2017/05/Mole-with-Turin-landscape-city-view.jpg",
    image_alt: "The Mole Antonelliana and 19th-century monuments",
    description: "Turin becomes the center of the Italian Risorgimento. Squares fill with celebratory statues and the city challenges gravity with the construction of the Mole Antonelliana.",
    interpretation: "The 19th century transforms Turin into an open-air monument, where bronze and masonry celebrate national unity and technological ambition.",
    artworkIds: ["statua-emanuele-filiberto", "mole-antonelliana"]
  },
  {
    id: "memorie-belliche",
    title: "Memories & Urban Traces",
    dateLabel: "XVIII - XX Century",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2025/02/palle-cannone-palazzi-torino-633x400.jpg",
    image_alt: "Details of embedded cannonballs",
    description: "The wounds of war and popular rituals leave material traces on the city body. Embedded bullets and monuments eroded by the touch of passers-by become part of the invisible heritage.",
    interpretation: "These traces interrupt the monumental narrative to tell a story of resistance, superstition, and daily life.",
    artworkIds: ["palle-cannone", "sommergibile-provana", "dito-colombo"]
  },
  {
    id: "torino-contemporanea",
    title: "Contemporary Turin",
    dateLabel: "XXI Century",
    image_url: "https://www.guidatorino.com/wp-content/uploads/2019/09/toro-esce-muro-torino.jpg",
    image_alt: "T'ORO by Richi Ferrero",
    description: "Post-industrial Turin opens up to new languages. Sound sculptures, installations that challenge facades, and bioarchitecture redefine the relationship between citizen and public space.",
    interpretation: "Contemporary art acts as a poetic explosion inside the historical fabric, inviting us to look at the city with new and curious eyes.",
    artworkIds: ["testa-michelangelo", "l-eco", "toro-muro", "palazzo-piercing", "condominio-25-verde", "panchina-innamorati", "orso-bordalo"]
  },
  {
    id: "museo-urbano",
    title: "MAU: Museum of Urban Art",
    dateLabel: "Present",
    image_url: "https://www.museoarteurbana.it/wp-content/uploads/2023/12/fanti-1024x768.jpg",
    image_alt: "The murals of Borgo Campidoglio",
    description: "Borgo Campidoglio becomes an open-air museum where building facades host murals and installations. Art is no longer exclusive to museums, but lives in the neighborhood streets.",
    interpretation: "The MAU demonstrates that urban heritage is alive and participatory: every wall can become a canvas for collective memory and daily beauty.",
    artworkIds: ["mau-assenza", "mau-campidoglius", "mau-freedom", "mau-cor-lesu"]
  }
];
